import { HairStyle, Question } from './types';

export const HAIRSTYLES: Record<string, HairStyle> = {
    as_perm: {
        id: 'as_perm',
        name: 'As Perm',
        nameKo: '애즈펌 (As Perm)',
        position: '현재 국내 남자 펌의 기준값',
        description: '꾸안꾸의 정석. 이마를 살짝만 보여줘서 부담스럽지 않고 자연스러워요.',
        tags: ['자연스러움', '부드러운 인상', '국민 헤어'],
        badMatch: ['강한 인상 원함', '이마 완전 오픈'],
        imagePath: '/images/characters/as_perm.png',
    },
    garma_perm: {
        id: 'garma_perm',
        name: 'Garma Perm',
        nameKo: '가르마펌 (Garma Perm)',
        position: '애즈펌 다음으로 많이 선택됨',
        description: '이마를 시원하게 드러내어 신뢰감 있고 지적인 이미지를 줍니다.',
        tags: ['지적인', '신뢰감', '성숙함'],
        badMatch: ['넓은 이마 컴플렉스', 'M자 라인'],
        imagePath: '/images/characters/garma_perm.png',
    },
    see_through_cut: {
        id: 'see_through_cut',
        name: 'See-Through Cut',
        nameKo: '시스루컷 (See-Through Cut)',
        position: '요즘 20대에서 급상승',
        description: '답답한 바가지 머리는 그만. 가벼운 앞머리로 트렌디하고 영한 느낌!',
        tags: ['트렌디', '청량함', '어려보임'],
        badMatch: ['무거운 앞머리 선호', '곱슬이 심함'],
        imagePath: '/images/characters/see_through_cut.png',
    },
    shadow_perm: {
        id: 'shadow_perm',
        name: 'Shadow Perm',
        nameKo: '쉐도우펌 (Shadow Perm)',
        position: '애즈펌보다 살짝 더 펌 느낌',
        description: '볼륨감이 살아있는 S컬 웨이브. 직모라 볼륨이 죽는 분들에게 최고.',
        tags: ['볼륨감', '귀여운', '동안'],
        badMatch: ['머리 커보이는거 싫음', '부스스함 싫음'],
        imagePath: '/images/characters/shadow_perm.png',
    },
    sleek_cut: {
        id: 'sleek_cut',
        name: 'Sleek Cut',
        nameKo: '슬릭컷 (Sleek Cut)',
        position: '성숙·미니멀 트렌드',
        description: '세련되고 날렵한 도시 남자. 제품을 발라 딱 붙인 느낌이 핵심.',
        tags: ['섹시한', '도회적', '깔끔함'],
        badMatch: ['제품 바르기 귀찮음', '두상 컴플렉스'],
        imagePath: '/images/characters/sleek_cut.png',
    },
    crop_cut: {
        id: 'crop_cut',
        name: 'Crop Cut',
        nameKo: '크롭컷 (Crop Cut)',
        position: '스트리트·무심 스타일',
        description: '짧고 강렬한 남성미. 손질이 필요 없이 털고 나가면 끝!',
        tags: ['상남자', '편리함', '힙스터'],
        badMatch: ['긴 얼굴형', '부드러운 이미지'],
        imagePath: '/images/characters/crop_cut.png',
    },
    hippie_perm: {
        id: 'hippie_perm',
        name: 'Hippie Perm',
        nameKo: '히피펌 (Hippie Perm)',
        position: '개성파 + 예술/패션 감도',
        description: '자유로운 영혼의 힙한 무드. 젖은 머리 스타일링과 찰떡궁합.',
        tags: ['개성파', '자유분방', '아티스트'],
        badMatch: ['단정한 직장인', '깔끔한거 선호'],
        imagePath: '/images/characters/hippie_perm.png',
    },
};

export const FEMALE_HAIRSTYLES: Record<string, HairStyle> = {
    tassel_cut: {
        id: 'tassel_cut',
        name: 'Tassel Cut',
        nameKo: '태슬컷 (Tassel Cut)',
        position: '칼단발의 정석',
        description: '똑 떨어지는 일자 라인이 시크하고 도도해 보여요. 턱선이 갸름해 보이는 효과!',
        tags: ['시크', '도회적', '세련됨'],
        badMatch: ['사각턱 부각될 수 있음', '곱슬 심함'],
        imagePath: '/images/characters/female/tassel_cut.png',
    },
    hash_cut: {
        id: 'hash_cut',
        name: 'Hash Cut',
        nameKo: '허쉬컷 (Hash Cut)',
        position: '힙한 숏/중단발',
        description: '가벼운 층을 많이 내어 보이쉬하면서도 자유분방한 느낌을 줍니다.',
        tags: ['힙함', '중성적', '가벼움'],
        badMatch: ['숱이 너무 없으면 휑함', '단정함 선호'],
        imagePath: '/images/characters/female/hash_cut.png',
    },
    wendy_cut: {
        id: 'wendy_cut',
        name: 'Wendy Cut',
        nameKo: '웬디컷 (Wendy Cut)',
        position: '국민 중단발',
        description: '얼굴을 감싸는 부드러운 층이 광대를 커버하고 청순한 분위기를 연출해요.',
        tags: ['청순', '얼굴소멸', '러블리'],
        badMatch: ['층 낸 머리 싫음', '무거운 느낌 선호'],
        imagePath: '/images/characters/female/wendy_cut.png',
    },
    build_perm: {
        id: 'build_perm',
        name: 'Build Perm',
        nameKo: '빌드펌 (Build Perm)',
        position: '여성스러운 S컬',
        description: 'C컬과 S컬이 섞여 풍성하고 우아한 볼륨을 만들어주는 스타일입니다.',
        tags: ['우아함', '여신머리', '볼륨'],
        badMatch: ['손질 귀찮음', '직선적인 느낌 선호'],
        imagePath: '/images/characters/female/build_perm.png',
    },
    hush_cut: {
        id: 'hush_cut',
        name: 'Hush Cut',
        nameKo: '장발 허쉬컷 (Long Hush)',
        position: '트렌디한 장발',
        description: '긴 기장에서도 가벼운 질감을 살려 스타일리시하고 힙한 무드를 줍니다.',
        tags: ['유니크', '트렌디', '힙스터'],
        badMatch: ['날리는 머리 싫음', '깔끔함 선호'],
        imagePath: '/images/characters/female/hush_cut.png',
    },
    elizabeth_perm: {
        id: 'elizabeth_perm',
        name: 'Elizabeth Perm',
        nameKo: '엘리자벳펌 (Elizabeth)',
        position: '우아함의 끝판왕',
        description: '굵은 웨이브가 얼굴 옆라인을 따라 흐르며 화려하고 고급스러운 이미지를 줍니다.',
        tags: ['화려함', '고급스러움', '페미닌'],
        badMatch: ['짧은 머리 선호', '자연스러움 추구'],
        imagePath: '/images/characters/female/elizabeth_perm.png',
    },
    sleek_cut_w: {
        id: 'sleek_cut_w',
        name: 'Sleek Cut',
        nameKo: '슬릭컷 (Sleek Cut)',
        position: '뉴진스 스타일',
        description: '매직한 듯 찰랑거리는 긴 생머리. 청초하면서도 시크한 매력이 있어요.',
        tags: ['청순', '시크', 'Y2K'],
        badMatch: ['긴 얼굴형', '볼륨 필요함'],
        imagePath: '/images/characters/female/sleek_cut.png',
    },
    hippie_perm_w: {
        id: 'hippie_perm_w',
        name: 'Hippie Perm',
        nameKo: '젤리/히피펌 (Jelly Perm)',
        position: '통통 튀는 개성',
        description: '뿌리부터 흐르는 컬이 몽환적이고 사랑스러운 빈티지 무드를 완성합니다.',
        tags: ['러블리', '빈티지', '개성'],
        badMatch: ['부스스함 못참음', '단정함 필수'],
        imagePath: '/images/characters/female/hippie_perm.png',
    },
};

export const QUESTIONS: Question[] = [
    {
        id: 'forehead',
        title: 'Q1. 원하는 이마 노출 정도는?',
        options: [
            { value: 'none', label: '완전 덮기', description: '이마 보이는 건 부끄러워요' },
            { value: 'little', label: '살짝만 보이기', description: '답답한 건 싫지만 다 까긴 부담' },
            { value: 'full', label: '시원하게 까기', description: '이마 미남, 자신감 뿜뿜' },
        ],
    },
    {
        id: 'vibe',
        title: 'Q2. 평소 추구하는 분위기는?',
        options: [
            { value: 'standard', label: '깔끔/단정', description: '호불호 없는 훈남 스타일' },
            { value: 'character', label: '힙함/개성', description: '나만의 색깔이 뚜렷했으면' },
            { value: 'natural', label: '자연스러움', description: '꾸민 듯 안 꾸민 듯 편안함' },
        ],
    },
    {
        id: 'maintenance',
        title: 'Q3. 아침에 머리 손질, 얼마나 가능?',
        options: [
            { value: 'none', label: '3분 컷', description: '그냥 털고 나가고 싶어요' },
            { value: 'basic', label: '드라이 정도는', description: '말릴 때 모양 잡을 수 있어요' },
            { value: 'hard', label: '각 잡고 꾸밈', description: '왁스/스프레이 사용 가능!' },
        ],
    },
];

export const FEMALE_QUESTIONS: Question[] = [
    {
        id: 'forehead', // Re-using ID for simplicity in state, but logic will interpret it as Length
        title: 'Q1. 현재(또는 원하는) 기장은?',
        options: [
            { value: 'short', label: '숏/단발', description: '목선이 드러나는 산뜻한 기장' },
            { value: 'medium', label: '중단발 (거지존)', description: '어깨에 닿는 애매한 기장' },
            { value: 'long', label: '장발', description: '가슴 아래로 내려오는 긴 머리' },
        ],
    },
    {
        id: 'vibe',
        title: 'Q2. 원하는 분위기는?',
        options: [
            { value: 'lovely', label: '러블리/큐티', description: '사랑스럽고 귀여운 느낌' },
            { value: 'chic', label: '시크/힙', description: '도시적이고 세련된 느낌' },
            { value: 'innocent', label: '청순/자연스러움', description: '깨끗하고 부드러운 이미지' },
        ],
    },
    {
        id: 'maintenance',
        title: 'Q3. 손질 선호도',
        options: [
            { value: 'easy', label: '털어 말리기만', description: '손질 귀찮아요, 편한 게 최고' },
            { value: 'hard', label: '고데기/드라기 가능', description: '예뻐질 수 있다면 감수함!' },
        ],
    },
];
