import { HairStyle, Question } from './types';

export const HAIRSTYLES: Record<string, HairStyle> = {
    as_perm: {
        id: 'as_perm',
        name: 'As Perm',
        nameKo: '애즈펌 (As Perm)',
        position: 'Standard of K-Perm',
        positionKo: '현재 국내 남자 펌의 기준값',
        description: 'Effortless chic. Slightly exposed forehead for a natural, burden-free look.',
        descriptionKo: '꾸안꾸의 정석. 이마를 살짝만 보여줘서 부담스럽지 않고 자연스러워요.',
        tags: ['Natural', 'Soft', 'Standard'],
        tagsKo: ['자연스러움', '부드러운 인상', '국민 헤어'],
        badMatch: ['Strong Image', 'Full Forehead'],
        badMatchKo: ['강한 인상 원함', '이마 완전 오픈'],
        imagePath: '/images/characters/as_perm.png',
    },
    garma_perm: {
        id: 'garma_perm',
        name: 'Garma Perm',
        nameKo: '가르마펌 (Garma Perm)',
        position: 'Most popular after As-Perm',
        positionKo: '애즈펌 다음으로 많이 선택됨',
        description: 'Cool open forehead giving an intelligent and trustworthy image.',
        descriptionKo: '이마를 시원하게 드러내어 신뢰감 있고 지적인 이미지를 줍니다.',
        tags: ['Intelligent', 'Trust', 'Mature'],
        tagsKo: ['지적인', '신뢰감', '성숙함'],
        badMatch: ['Wide Forehead', 'M-Shape Hairline'],
        badMatchKo: ['넓은 이마 컴플렉스', 'M자 라인'],
        imagePath: '/images/characters/garma_perm.png',
    },
    see_through_cut: {
        id: 'see_through_cut',
        name: 'See-Through Cut',
        nameKo: '시스루컷 (See-Through Cut)',
        position: 'Trending for 20s',
        positionKo: '요즘 20대에서 급상승',
        description: 'No more heavy bowl cuts. Light bangs for a trendy and young vibe!',
        descriptionKo: '답답한 바가지 머리는 그만. 가벼운 앞머리로 트렌디하고 영한 느낌!',
        tags: ['Trendy', 'Young', 'Clean'],
        tagsKo: ['트렌디', '청량함', '어려보임'],
        badMatch: ['Heavy Bangs', 'Curly Hair'],
        badMatchKo: ['무거운 앞머리 선호', '곱슬이 심함'],
        imagePath: '/images/characters/see_through_cut.png',
    },
    shadow_perm: {
        id: 'shadow_perm',
        name: 'Shadow Perm',
        nameKo: '쉐도우펌 (Shadow Perm)',
        position: 'More volume than As-Perm',
        positionKo: '애즈펌보다 살짝 더 펌 느낌',
        description: 'S-curl wave with volume. Best for straight hair that falls flat.',
        descriptionKo: '볼륨감이 살아있는 S컬 웨이브. 직모라 볼륨이 죽는 분들에게 최고.',
        tags: ['Volume', 'Cute', 'Youth'],
        tagsKo: ['볼륨감', '귀여운', '동안'],
        badMatch: ['Big Head', 'Hate Frizz'],
        badMatchKo: ['머리 커보이는거 싫음', '부스스함 싫음'],
        imagePath: '/images/characters/shadow_perm.png',
    },
    sleek_cut: {
        id: 'sleek_cut',
        name: 'Sleek Cut',
        nameKo: '슬릭컷 (Sleek Cut)',
        position: 'Mature & Minimal Trend',
        positionKo: '성숙·미니멀 트렌드',
        description: 'Sharp urban look. Styled flat and tight with product.',
        descriptionKo: '세련되고 날렵한 도시 남자. 제품을 발라 딱 붙인 느낌이 핵심.',
        tags: ['Sexy', 'Urban', 'Clean'],
        tagsKo: ['섹시한', '도회적', '깔끔함'],
        badMatch: ['No Styling', 'Head Shape issues'],
        badMatchKo: ['제품 바르기 귀찮음', '두상 컴플렉스'],
        imagePath: '/images/characters/sleek_cut.png',
    },
    crop_cut: {
        id: 'crop_cut',
        name: 'Crop Cut',
        nameKo: '크롭컷 (Crop Cut)',
        position: 'Street & Unique',
        positionKo: '스트리트·무심 스타일',
        description: 'Short and strong masculinity. Just shake and go!',
        descriptionKo: '짧고 강렬한 남성미. 손질이 필요 없이 털고 나가면 끝!',
        tags: ['Masculine', 'Easy', 'Hip'],
        tagsKo: ['상남자', '편리함', '힙스터'],
        badMatch: ['Long Face', 'Soft Image'],
        badMatchKo: ['긴 얼굴형', '부드러운 이미지'],
        imagePath: '/images/characters/crop_cut.png',
    },
    hippie_perm: {
        id: 'hippie_perm',
        name: 'Hippie Perm',
        nameKo: '히피펌 (Hippie Perm)',
        position: 'Unique & Artistic',
        positionKo: '개성파 + 예술/패션 감도',
        description: 'Free-spirited hip mood. Perfect match with wet styling.',
        descriptionKo: '자유로운 영혼의 힙한 무드. 젖은 머리 스타일링과 찰떡궁합.',
        tags: ['Unique', 'Free', 'Artist'],
        tagsKo: ['개성파', '자유분방', '아티스트'],
        badMatch: ['Office Look', 'Too Clean'],
        badMatchKo: ['단정한 직장인', '깔끔한거 선호'],
        imagePath: '/images/characters/hippie_perm.png',
    },
};

export const FEMALE_HAIRSTYLES: Record<string, HairStyle> = {
    tassel_cut: {
        id: 'tassel_cut',
        name: 'Tassel Cut',
        nameKo: '태슬컷 (Tassel Cut)',
        position: 'Standard Short Bob',
        positionKo: '칼단발의 정석',
        description: 'Chic and straight line. Makes the jawline look slimmer!',
        descriptionKo: '똑 떨어지는 일자 라인이 시크하고 도도해 보여요. 턱선이 갸름해 보이는 효과!',
        tags: ['Chic', 'Urban', 'Stylish'],
        tagsKo: ['시크', '도회적', '세련됨'],
        badMatch: ['Square Jaw', 'Heavy Curl'],
        badMatchKo: ['사각턱 부각될 수 있음', '곱슬 심함'],
        imagePath: '/images/characters/female/tassel_cut.png',
    },
    hash_cut: {
        id: 'hash_cut',
        name: 'Hash Cut',
        nameKo: '허쉬컷 (Hash Cut)',
        position: 'Hip Short/Mid',
        positionKo: '힙한 숏/중단발',
        description: 'Boyish yet free feeling with lots of layers.',
        descriptionKo: '가벼운 층을 많이 내어 보이쉬하면서도 자유분방한 느낌을 줍니다.',
        tags: ['Hip', 'Unisex', 'Light'],
        tagsKo: ['힙함', '중성적', '가벼움'],
        badMatch: ['Thin Hair', 'Neat Look'],
        badMatchKo: ['숱이 너무 없으면 휑함', '단정함 선호'],
        imagePath: '/images/characters/female/hash_cut.png',
    },
    wendy_cut: {
        id: 'wendy_cut',
        name: 'Wendy Cut',
        nameKo: '웬디컷 (Wendy Cut)',
        position: 'National Mid-length',
        positionKo: '국민 중단발',
        description: 'Soft layers wrapping the face cover cheekbones and create an innocent vibe.',
        descriptionKo: '얼굴을 감싸는 부드러운 층이 광대를 커버하고 청순한 분위기를 연출해요.',
        tags: ['Innocent', 'Face Cover', 'Lovely'],
        tagsKo: ['청순', '얼굴소멸', '러블리'],
        badMatch: ['Hate Layers', 'Heavy Look'],
        badMatchKo: ['층 낸 머리 싫음', '무거운 느낌 선호'],
        imagePath: '/images/characters/female/wendy_cut.png',
    },
    build_perm: {
        id: 'build_perm',
        name: 'Build Perm',
        nameKo: '빌드펌 (Build Perm)',
        position: 'Feminine S-Curl',
        positionKo: '여성스러운 S컬',
        description: 'Mix of C and S curls creating rich and elegant volume.',
        descriptionKo: 'C컬과 S컬이 섞여 풍성하고 우아한 볼륨을 만들어주는 스타일입니다.',
        tags: ['Elegant', 'Goddess', 'Volume'],
        tagsKo: ['우아함', '여신머리', '볼륨'],
        badMatch: ['Lazy', 'Straight Look'],
        badMatchKo: ['손질 귀찮음', '직선적인 느낌 선호'],
        imagePath: '/images/characters/female/build_perm.png',
    },
    hush_cut: {
        id: 'hush_cut',
        name: 'Hush Cut',
        nameKo: '장발 허쉬컷 (Long Hush)',
        position: 'Trendy Long',
        positionKo: '트렌디한 장발',
        description: 'Stylish and hip mood with light textures even on long hair.',
        descriptionKo: '긴 기장에서도 가벼운 질감을 살려 스타일리시하고 힙한 무드를 줍니다.',
        tags: ['Unique', 'Trendy', 'Hipster'],
        tagsKo: ['유니크', '트렌디', '힙스터'],
        badMatch: ['Messy', 'Neat Look'],
        badMatchKo: ['날리는 머리 싫음', '깔끔함 선호'],
        imagePath: '/images/characters/female/hush_cut.png',
    },
    elizabeth_perm: {
        id: 'elizabeth_perm',
        name: 'Elizabeth Perm',
        nameKo: '엘리자벳펌 (Elizabeth)',
        position: 'Ultimate Elegance',
        positionKo: '우아함의 끝판왕',
        description: 'Thick waves flowing along the side face create a glamorous and luxurious image.',
        descriptionKo: '굵은 웨이브가 얼굴 옆라인을 따라 흐르며 화려하고 고급스러운 이미지를 줍니다.',
        tags: ['Glam', 'Luxury', 'Feminine'],
        tagsKo: ['화려함', '고급스러움', '페미닌'],
        badMatch: ['Hate Short', 'Natural Look'],
        badMatchKo: ['짧은 머리 선호', '자연스러움 추구'],
        imagePath: '/images/characters/female/elizabeth_perm.png',
    },
    sleek_cut_w: {
        id: 'sleek_cut_w',
        name: 'Sleek Cut',
        nameKo: '슬릭컷 (Sleek Cut)',
        position: 'NewJeans Style',
        positionKo: '뉴진스 스타일',
        description: 'Long straight hair like magic. Pure yet chic charm.',
        descriptionKo: '매직한 듯 찰랑거리는 긴 생머리. 청초하면서도 시크한 매력이 있어요.',
        tags: ['Pure', 'Chic', 'Y2K'],
        tagsKo: ['청순', '시크', 'Y2K'],
        badMatch: ['Long Face', 'Need Volume'],
        badMatchKo: ['긴 얼굴형', '볼륨 필요함'],
        imagePath: '/images/characters/female/sleek_cut.png',
    },
    hippie_perm_w: {
        id: 'hippie_perm_w',
        name: 'Hippie Perm',
        nameKo: '젤리/히피펌 (Jelly Perm)',
        position: 'Pop & Unique',
        positionKo: '통통 튀는 개성',
        description: 'Curls flowing from roots complete a dreamy and lovely vintage mood.',
        descriptionKo: '뿌리부터 흐르는 컬이 몽환적이고 사랑스러운 빈티지 무드를 완성합니다.',
        tags: ['Lovely', 'Vintage', 'Unique'],
        tagsKo: ['러블리', '빈티지', '개성'],
        badMatch: ['Hate Frizz', 'Neat Look'],
        badMatchKo: ['부스스함 못참음', '단정함 필수'],
        imagePath: '/images/characters/female/hippie_perm.png',
    },
};

export const QUESTIONS: Question[] = [
    {
        id: 'forehead',
        title: 'Q1. How much forehead exposure?',
        titleKo: 'Q1. 원하는 이마 노출 정도는?',
        options: [
            { value: 'none', label: 'Cover Full', labelKo: '완전 덮기', description: 'Shy about forehead', descriptionKo: '이마 보이는 건 부끄러워요' },
            { value: 'little', label: 'Slightly Open', labelKo: '살짝만 보이기', description: 'Not too open, not too closed', descriptionKo: '답답한 건 싫지만 다 까긴 부담' },
            { value: 'full', label: 'Full Open', labelKo: '시원하게 까기', description: 'Confident with forehead', descriptionKo: '이마 미남, 자신감 뿜뿜' },
        ],
    },
    {
        id: 'vibe',
        title: 'Q2. What vibe do you prefer?',
        titleKo: 'Q2. 평소 추구하는 분위기는?',
        options: [
            { value: 'standard', label: 'Neat & Standard', labelKo: '깔끔/단정', description: 'Standard handsome look', descriptionKo: '호불호 없는 훈남 스타일' },
            { value: 'character', label: 'Hip & Unique', labelKo: '힙함/개성', description: 'Distinct self-style', descriptionKo: '나만의 색깔이 뚜렷했으면' },
            { value: 'natural', label: 'Natural', labelKo: '자연스러움', description: 'Effortless look', descriptionKo: '꾸민 듯 안 꾸민 듯 편안함' },
        ],
    },
    {
        id: 'maintenance',
        title: 'Q3. Styling time in morning?',
        titleKo: 'Q3. 아침에 머리 손질, 얼마나 가능?',
        options: [
            { value: 'none', label: '3 Mins', labelKo: '3분 컷', description: 'Just shake and go', descriptionKo: '그냥 털고 나가고 싶어요' },
            { value: 'basic', label: 'Blow Dry', labelKo: '드라이 정도는', description: 'Can shape with dryer', descriptionKo: '말릴 때 모양 잡을 수 있어요' },
            { value: 'hard', label: 'Full Styling', labelKo: '각 잡고 꾸밈', description: 'Wax/Spray is fine', descriptionKo: '왁스/스프레이 사용 가능!' },
        ],
    },
];

export const FEMALE_QUESTIONS: Question[] = [
    {
        id: 'forehead',
        title: 'Q1. Current (or desired) Length?',
        titleKo: 'Q1. 현재(또는 원하는) 기장은?',
        options: [
            { value: 'short', label: 'Short/Bob', labelKo: '숏/단발', description: 'Fresh neck line', descriptionKo: '목선이 드러나는 산뜻한 기장' },
            { value: 'medium', label: 'Medium', labelKo: '중단발 (거지존)', description: 'Shoulder length', descriptionKo: '어깨에 닿는 애매한 기장' },
            { value: 'long', label: 'Long', labelKo: '장발', description: 'Below chest', descriptionKo: '가슴 아래로 내려오는 긴 머리' },
        ],
    },
    {
        id: 'vibe',
        title: 'Q2. Desired Vibe?',
        titleKo: 'Q2. 원하는 분위기는?',
        options: [
            { value: 'lovely', label: 'Lovely/Cute', labelKo: '러블리/큐티', description: 'Adorable image', descriptionKo: '사랑스럽고 귀여운 느낌' },
            { value: 'chic', label: 'Chic/Hip', labelKo: '시크/힙', description: 'Urban & Stylish', descriptionKo: '도시적이고 세련된 느낌' },
            { value: 'innocent', label: 'Innocent/Natural', labelKo: '청순/자연스러움', description: 'Clean & Soft', descriptionKo: '깨끗하고 부드러운 이미지' },
        ],
    },
    {
        id: 'maintenance',
        title: 'Q3. Styling Preference',
        titleKo: 'Q3. 손질 선호도',
        options: [
            { value: 'easy', label: 'Easy Dry', labelKo: '털어 말리기만', description: 'Hate styling, comfort first', descriptionKo: '손질 귀찮아요, 편한 게 최고' },
            { value: 'hard', label: 'Iron/Dryer', labelKo: '고데기/드라기 가능', description: 'Beauty over comfort', descriptionKo: '예뻐질 수 있다면 감수함!' },
        ],
    },
];
