'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ko' | 'en' | 'ja' | 'zh' | 'vn' | 'th';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: Language; label: string; flag: string; }[] = [
    { code: 'ko', label: '한국어', flag: '🇰🇷' },
    { code: 'en', label: 'English', flag: '🇺🇸' },
    { code: 'ja', label: '日本語', flag: '🇯🇵' },
    { code: 'zh', label: '中文', flag: '🇨🇳' },
    { code: 'vn', label: 'Tiếng Việt', flag: '🇻🇳' },
    { code: 'th', label: 'ไทย', flag: '🇹🇭' },
];

export const translations = {
    en: {
        analysisResult: "Analysis Result",
        bestMatch: "BEST MATCH",
        matchScore: "Match Score",
        whyItFits: "Why it fits you",
        aiGenerate: "AI Generate",
        reset: "Reset",
        download: "Download",
        findSalon: "Find Salon",
        complementaryTips: "Complementary Tips",
        stylingDifficulty: "Styling Difficulty",
        subscribeTitle: "Unlock Premium Report",
        subscribeDesc: "Get detailed face symmetry & personal color analysis.",
        subscribeBtn: "Subscribe - $2.99/mo",
        // Logic / Tags
        'clean': 'Clean',
        'pro': 'Professional',
        'short': 'Short',
        'easy-care': 'Easy Care',
        'trendy': 'Trendy',
        'manly': 'Masculine',
        'soft': 'Soft',
        'volume': 'Volume',
        'hip': 'Hip',
        'unique': 'Unique',
        'classic': 'Classic',
        'feminine': 'Feminine',
        'chic': 'Chic',
        'goddess': 'Goddess',
        'cute': 'Cute',
        'lovely': 'Lovely',
        'elegant': 'Elegant',
        'mature': 'Mature',
        'pure': 'Pure',
        'boyish': 'Boyish',
        'styling': 'Styling',
        'natural': 'Natural',
        'young': 'Young',
        'sharp': 'Sharp',
        'medium-care': 'Medium Care',
        'high-care': 'High Care',
        'flat': 'Flat',
        'retro': 'Retro',
        'daily': 'Daily',
        'long': 'Long',
        'medium': 'Medium',
        // Reasons
        'reason_face_good': 'Great for your face shape',
        'reason_face_bad': 'May highlight face shape concerns',
        'reason_texture_good': 'Matches your hair texture',
        'reason_texture_bad': 'Texture mismatch',
        'reason_vibe_good': 'Matches desired vibe',
        'reason_maintenance_bad': 'High maintenance',
        'reason_length_cut': 'Good short option',
        'reason_length_grow': 'Good long option',
        'reason_length_keep': 'Maintains current length',

        // Landing Page
        landingTitle1: 'Find Your',
        landingTitle2: 'Perfect Fit',
        landingSubtitle: 'AI analyzes your face shape and hair texture\nto find the perfect hairstyle for you.',
        startAnalysis: 'Start Free Analysis',
        dataPrivacy: '*Photos are processed locally and never saved on server.',
        featureFace: 'Face Analysis',
        featureStyle: 'Style Recs',
        featureReport: 'Custom Report',

        // Wizard
        selectGender: 'Select Gender',
        uploadPhoto: 'Upload Photo',
        or: 'or',
        selfCheckBtn: 'Self Check without Photo',
        analyzing: 'AI Analyzing...',
        selfCheckTitle: 'What is your face shape?',
        selfCheckDesc: 'Choose the shape that fits you best.',
        styleCheck: 'Style Check',
        myStyleCheck: 'My Style Check',
        uploadGuide: 'Please upload a front-facing photo.',
        failAnalysis: 'Analysis failed. Please check the photo.',
        aiAnalysisResult: 'AI Face Analysis Result',
        mainShape: 'Main Shape',
        manualResult: 'Self Check Result',
        selectedShape: 'Selected Shape',
        resultDesc: '* Based on the analysis and your answers, we recommend',
        resultDescEnd: '.',
        manualDesc: '* Recommended style based on your selection.',
        simulateOnMyFace: 'Simulate on my face',
        requestTemplate: 'Salon Request Template',
        showDesigner: 'Show this screen to your designer.',
        maintenanceTip: 'Maintenance Tip',
        otherRecs: 'Other Recommendations',
        // Face Shape Descriptions
        desc_oval: 'Slim and balanced line like an egg',
        desc_round: 'Round and soft impression',
        desc_square: 'Strong, angular jawline',
        desc_long: 'Longer vertical proportions',
        desc_heart: 'Wide forehead, pointed chin',
        desc_diamond: 'Prominent cheekbones, pointed chin',
        desc_triangle: 'Jawline wider than forehead',
    },
    ko: {
        analysisResult: "분석 결과",
        bestMatch: "최고의 추천",
        matchScore: "일치도",
        whyItFits: "추천 이유",
        aiGenerate: "AI 가상 착용",
        reset: "초기화",
        download: "저장",
        findSalon: "미용실 찾기",
        complementaryTips: "스타일링 꿀팁",
        stylingDifficulty: "손질 난이도",
        subscribeTitle: "프리미엄 리포트 잠금 해제",
        subscribeDesc: "얼굴 비대칭 및 퍼스널 컬러 상세 분석을 확인하세요.",
        subscribeBtn: "구독하기 - 월 2,900원",
        // Logic / Tags
        'clean': '깔끔한',
        'pro': '전문적인',
        'short': '짧은 기장',
        'easy-care': '손질 쉬움',
        'trendy': '트렌디',
        'manly': '남성적인',
        'soft': '의 부드러운',
        'volume': '볼륨감',
        'hip': '힙한',
        'unique': '유니크',
        'classic': '클래식',
        'feminine': '여성스러운',
        'chic': '시크한',
        'goddess': '여신머리',
        'cute': '귀여운',
        'lovely': '사랑스러운',
        'elegant': '우아한',
        'mature': '성숙한',
        'pure': '청순한',
        'boyish': '보이시',
        'styling': '스타일링',
        'natural': '자연스러운',
        'young': '어려보이는',
        'sharp': '날렵한',
        'medium-care': '손질 보통',
        'high-care': '손질 어려움',
        'flat': '플랫한',
        'retro': '레트로',
        'daily': '데일리',
        'long': '긴 기장',
        'medium': '중단발',
        // Reasons
        'reason_face_good': '얼굴형 보완에 탁월해요',
        'reason_face_bad': '얼굴형 단점이 부각될 수 있어요',
        'reason_texture_good': '현재 모발과 찰떡이에요',
        'reason_texture_bad': '모발 성질과 안 맞을 수 있어요',
        'reason_vibe_good': '원하는 분위기에 딱 맞아요',
        'reason_maintenance_bad': '손질이 조금 필요해요',
        'reason_length_cut': '원하시는 짧은 스타일이에요',
        'reason_length_grow': '원하시는 긴 스타일이에요',
        'reason_length_keep': '현재 기장을 유지해요',

        // Landing Page
        landingTitle1: '나만의',
        landingTitle2: '인생 머리 찾기',
        landingSubtitle: 'AI가 얼굴형, 두상, 모질을 분석하여\n당신에게 가장 잘 어울리는 인생 머리를 찾아드려요.',
        startAnalysis: '무료로 분석 시작하기',
        dataPrivacy: '*사진은 서버에 저장되지 않고 100% 안전하게 처리됩니다.',
        featureFace: '얼굴형 분석',
        featureStyle: '스타일 추천',
        featureReport: '맞춤 리포트',

        // Data Values
        male: '남성',
        female: '여성',
        shape_oval: '계란형',
        shape_round: '둥근형',
        shape_square: '각형',
        shape_long: '긴 얼굴형',
        shape_heart: '하트형',
        shape_diamond: '다이아몬드형',
        shape_triangle: '삼각형',

        // Wizard
        selectGender: '성별을 선택해주세요',
        uploadPhoto: '사진 업로드',
        or: '또는',
        selfCheckBtn: '사진 없이 자가진단하기',
        analyzing: 'AI 분석중...',
        selfCheckTitle: '본인의 얼굴형은?',
        selfCheckDesc: '가장 가깝다고 생각되는 형태를 골라주세요.',
        styleCheck: '스타일 체크',
        myStyleCheck: 'My 스타일 체크',
        uploadGuide: '정면 사진을 올려주세요.',
        failAnalysis: '얼굴 분석 실패. 사진을 확인해주세요.',
        aiAnalysisResult: 'AI 얼굴형 분석 결과',
        mainShape: 'Main Shape',
        manualResult: '자가진단 결과',
        selectedShape: '선택한 얼굴형',
        resultDesc: '* 위 분석 결과와 서베이 답변을 종합하여',
        resultDescEnd: '을(를) 추천했습니다.',
        manualDesc: '* 사용자가 선택한 얼굴형과 답변을 기반으로 추천된 스타일입니다.',
        simulateOnMyFace: '내 얼굴에 합성해보기',
        requestTemplate: '미용실 요청 템플릿',
        showDesigner: '디자이너에게 이 화면을 보여주세요.',
        maintenanceTip: 'Maintenance Tip',
        otherRecs: '다른 추천 스타일',

        // Face Shape Descriptions
        desc_oval: '계란처럼 갸름한 라인',
        desc_round: '둥글고 부드러운 인상',
        desc_square: '턱선이 각지고 강인함',
        desc_long: '가로보다 세로가 김',
        desc_heart: '이마가 넓고 턱이 뾰족',
        desc_diamond: '광대가 있고 턱이 뾰족',
        desc_triangle: '이마보다 턱이 넓음',
        termsOfService: '이용약관',
        privacyPolicy: '개인정보처리방침',
    },
    ja: {
        analysisResult: "分析結果",
        bestMatch: "ベストマッチ",
        matchScore: "マッチ度",
        whyItFits: "おすすめの理由",
        aiGenerate: "AI仮想試着",
        reset: "リセット",
        download: "保存",
        findSalon: "美容室を探す",
        complementaryTips: "スタイリングのヒント",
        stylingDifficulty: "スタイリング難易度",
        subscribeTitle: "プレミアムレポートを解除",
        subscribeDesc: "顔の非対称性とパーソナルカラーの詳細分析を確認しましょう。",
        subscribeBtn: "購読する - 月額 2,900ウォン",
        // Logic / Tags
        'clean': '清潔感',
        'pro': 'プロフェッショナル',
        'short': 'ショート',
        'easy-care': '手入れ簡単',
        'trendy': 'トレンディ',
        'manly': '男性的',
        'soft': '柔らかい',
        'volume': 'ボリューム',
        'hip': 'ヒップ',
        'unique': 'ユニーク',
        'classic': 'クラシック',
        'feminine': 'フェミニン',
        'chic': 'シック',
        'goddess': '女神ヘア',
        'cute': 'キュート',
        'lovely': 'ラブリー',
        'elegant': 'エレガント',
        'mature': '大人っぽい',
        'pure': '清楚',
        'boyish': 'ボーイッシュ',
        'styling': 'スタイリング',
        'natural': 'ナチュラル',
        'young': '若々しい',
        'sharp': 'シャープ',
        'medium-care': '手入れ普通',
        'high-care': '手入れ難しい',
        'flat': 'フラット',
        'retro': 'レトロ',
        'daily': 'デイリー',
        'long': 'ロング',
        'medium': 'ミディアム',
        // Reasons
        'reason_face_good': '顔型をきれいに見せます',
        'reason_face_bad': '顔型の短所が目立つ可能性があります',
        'reason_texture_good': '現在の髪質にぴったりです',
        'reason_texture_bad': '髪質に合わない可能性があります',
        'reason_vibe_good': '希望の雰囲気に合っています',
        'reason_maintenance_bad': '少し手入れが必要です',
        'reason_length_cut': '希望のショートスタイルです',
        'reason_length_grow': '希望のロングスタイルです',
        'reason_length_keep': '現在の長さを維持します',

        // Landing Page
        landingTitle1: '自分だけの',
        landingTitle2: '人生ヘア探し',
        landingSubtitle: 'AIが顔型、頭の形、髪質を分析して\nあなたにぴったりの人生ヘアを見つけます。',
        startAnalysis: '無料分析を始める',
        dataPrivacy: '*写真はサーバーに保存されず、安全に処理されます。',
        featureFace: '顔型分析',
        featureStyle: 'スタイル推奨',
        featureReport: 'カスタムレポート',
        male: '男性',
        female: '女性',
        shape_oval: '卵型',
        shape_round: '丸顔',
        shape_square: 'ベース型',
        shape_long: '面長',
        shape_heart: '逆三角形',
        shape_diamond: 'ひし形',
        shape_triangle: '三角形',

        // Wizard
        selectGender: '性別を選択してください',
        uploadPhoto: '写真をアップロード',
        or: 'または',
        selfCheckBtn: '写真なしで自己診断する',
        analyzing: 'AI分析中...',
        selfCheckTitle: 'あなたの顔型は？',
        selfCheckDesc: '最も近いと思う形を選んでください。',
        styleCheck: 'スタイルチェック',
        myStyleCheck: 'マイスタイルチェック',
        uploadGuide: '正面の写真をアップロードしてください。',
        failAnalysis: '顔分析失敗。写真を確認してください。',
        aiAnalysisResult: 'AI顔型分析結果',
        mainShape: 'メイン顔型',
        manualResult: '自己診断結果',
        selectedShape: '選択した顔型',
        resultDesc: '* 上記の分析結果とアンケート回答を総合して、',
        resultDescEnd: 'を推奨しました。',
        manualDesc: '* ユーザーが選択した顔型と回答に基づいて推奨されたスタイルです。',
        simulateOnMyFace: '自分の顔でシミュレーション',
        requestTemplate: '美容室リクエストテンプレート',
        showDesigner: '美容師にこの画面を見せてください。',
        maintenanceTip: '管理のヒント',
        otherRecs: '他のおすすめスタイル',
        // Face Shape Descriptions
        desc_oval: '卵のようにすっきりとしたライン',
        desc_round: '丸くて柔らかい印象',
        desc_square: '顎のラインが角ばっていて強い',
        desc_long: '横より縦が長い',
        desc_heart: '額が広く顎が尖っている',
        desc_diamond: '頬骨が出ていて顎が尖っている',
        desc_triangle: '額より顎が広い',
        termsOfService: '利用規約',
        privacyPolicy: 'プライバシーポリシー',
    },
    zh: {
        analysisResult: "分析结果",
        bestMatch: "最佳推荐",
        matchScore: "匹配度",
        whyItFits: "推荐理由",
        aiGenerate: "AI虚拟试戴",
        reset: "重置",
        download: "保存",
        findSalon: "寻找理发店",
        complementaryTips: "造型小贴士",
        stylingDifficulty: "打理难度",
        subscribeTitle: "解锁高级报告",
        subscribeDesc: "查看面部不对称及个人色彩详细分析。",
        subscribeBtn: "订阅 - 2,900韩元/月",
        // Logic / Tags
        'clean': '干净',
        'pro': '专业',
        'short': '短发',
        'easy-care': '易打理',
        'trendy': '潮流',
        'manly': '男性化',
        'soft': '柔和',
        'volume': '蓬松',
        'hip': '嘻哈',
        'unique': '独特',
        'classic': '经典',
        'feminine': '女性化',
        'chic': '时尚',
        'goddess': '女神范',
        'cute': '可爱',
        'lovely': '甜美',
        'elegant': '优雅',
        'mature': '成熟',
        'pure': '清纯',
        'boyish': '少年感',
        'styling': '造型',
        'natural': '自然',
        'young': '减龄',
        'sharp': '利落',
        'medium-care': '打理普通',
        'high-care': '打理困难',
        'flat': '扁平',
        'retro': '复古',
        'daily': '日常',
        'long': '长发',
        'medium': '中长发',
        // Reasons
        'reason_face_good': '非常修饰脸型',
        'reason_face_bad': '可能会突出脸型缺点',
        'reason_texture_good': '非常适合当前发质',
        'reason_texture_bad': '可能不适合您的发质',
        'reason_vibe_good': '符合您想要的氛围',
        'reason_maintenance_bad': '需要一些打理',
        'reason_length_cut': '符合您想要的短发风格',
        'reason_length_grow': '符合您想要的长发风格',
        'reason_length_keep': '保持当前长度',

        // Landing Page
        landingTitle1: '寻找你的',
        landingTitle2: '人生发型',
        landingSubtitle: 'AI分析脸型、头型和发质\n为你找到最完美的人生发型。',
        startAnalysis: '开始免费分析',
        dataPrivacy: '*照片不会保存到服务器，100%安全处理。',
        featureFace: '脸型分析',
        featureStyle: '发型推荐',
        featureReport: '定制报告',
        male: '男性',
        female: '女性',
        shape_oval: '鹅蛋脸',
        shape_round: '圆脸',
        shape_square: '方脸',
        shape_long: '长脸',
        shape_heart: '心形脸',
        shape_diamond: '菱形脸',
        shape_triangle: '三角形脸',

        // Face Shape Descriptions
        desc_oval: '如鹅蛋般匀称的线条',
        desc_round: '圆润柔和的印象',
        desc_square: '下颌线条棱角分明',
        desc_long: '纵向比横向长',
        desc_heart: '额头宽下巴尖',
        desc_diamond: '颧骨突出下巴尖',
        desc_triangle: '下巴比额头宽',

        // Wizard
        selectGender: '请选择性别',
        uploadPhoto: '上传照片',
        or: '或',
        selfCheckBtn: '无照片自我诊断',
        analyzing: 'AI分析中...',
        selfCheckTitle: '你的脸型是？',
        selfCheckDesc: '请选择最接近的形状。',
        styleCheck: '风格检查',
        myStyleCheck: '我的风格检查',
        uploadGuide: '请上传正面照片。',
        failAnalysis: '脸部分析失败。请检查照片。',
        aiAnalysisResult: 'AI脸型分析结果',
        mainShape: '主要脸型',
        manualResult: '自我诊断结果',
        selectedShape: '选择的脸型',
        resultDesc: '* 综合以上分析结果和问卷回答，',
        resultDescEnd: '为您推荐。',
        manualDesc: '* 基于用户选择的脸型和回答推荐的风格。',
        simulateOnMyFace: '在我的脸上模拟',
        requestTemplate: '理发店请求模板',
        showDesigner: '请向发型师出示此屏幕。',
        maintenanceTip: '管理提示',
        otherRecs: '其他推荐风格',
    },
    vn: {
        analysisResult: "Kết Quả Phân Tích",
        bestMatch: "Phù Hợp Nhất",
        matchScore: "Điểm Phù Hợp",
        whyItFits: "Lý Do Phù Hợp",
        aiGenerate: "Thử Tóc AI",
        reset: "Đặt Lại",
        download: "Lưu",
        findSalon: "Tìm Salon",
        complementaryTips: "Mẹo Tạo Kiểu",
        stylingDifficulty: "Độ Khó Tạo Kiểu",
        subscribeTitle: "Mở Khóa Báo Cáo VIP",
        subscribeDesc: "Xem phân tích chi tiết bất đối xứng và màu sắc cá nhân.",
        subscribeBtn: "Đăng Ký - 2,900 KRW/tháng",
        // Logic / Tags
        'clean': 'Gọn gàng',
        'pro': 'Chuyên nghiệp',
        'short': 'Tóc ngắn',
        'easy-care': 'Dễ chăm sóc',
        'trendy': 'Thời thượng',
        'manly': 'Nam tính',
        'soft': 'Mềm mại',
        'volume': 'Phồng',
        'hip': 'Hip',
        'unique': 'Độc đáo',
        'classic': 'Cổ điển',
        'feminine': 'Nữ tính',
        'chic': 'Sang trọng',
        'goddess': 'Nữ thần',
        'cute': 'Dễ thương',
        'lovely': 'Đáng yêu',
        'elegant': 'Thanh lịch',
        'mature': 'Trưởng thành',
        'pure': 'Trong sáng',
        'boyish': 'Nghịch ngợm',
        'styling': 'Tạo kiểu',
        'natural': 'Tự nhiên',
        'young': 'Trẻ trung',
        'sharp': 'Sắc sảo',
        'medium-care': 'Chăm sóc bình thường',
        'high-care': 'Khó chăm sóc',
        'flat': 'Phẳng',
        'retro': 'Cổ điển',
        'daily': 'Hàng ngày',
        'long': 'Tóc dài',
        'medium': 'Tóc lỡ',
        // Reasons
        'reason_face_good': 'Tuyệt vời cho khuôn mặt của bạn',
        'reason_face_bad': 'Có thể làm lộ khuyết điểm khuôn mặt',
        'reason_texture_good': 'Phù hợp với chất tóc hiện tại',
        'reason_texture_bad': 'Không phù hợp với chất tóc',
        'reason_vibe_good': 'Phù hợp với phong cách mong muốn',
        'reason_maintenance_bad': 'Cần chăm sóc kỹ',
        'reason_length_cut': 'Kiểu tóc ngắn bạn muốn',
        'reason_length_grow': 'Kiểu tóc dài bạn muốn',
        'reason_length_keep': 'Giữ nguyên độ dài hiện tại',

        // Landing Page
        landingTitle1: 'Tìm Kiếm',
        landingTitle2: 'Kiểu Tóc Hoàn Hảo',
        landingSubtitle: 'AI phân tích khuôn mặt và chất tóc\nđể tìm kiểu tóc phù hợp nhất cho bạn.',
        startAnalysis: 'Bắt Đầu Phân Tích Miễn Phí',
        dataPrivacy: '*Ảnh được xử lý cục bộ và không bao giờ lưu trên máy chủ.',
        featureFace: 'Phân Tích Mặt',
        featureStyle: 'Gợi Ý Kiểu',
        featureReport: 'Báo Cáo Riêng',
        male: 'Nam',
        female: 'Nữ',
        shape_oval: 'Trái xoan',
        shape_round: 'Tròn',
        shape_square: 'Vuông',
        shape_long: 'Dài',
        shape_heart: 'Trái tim',
        shape_diamond: 'Kim cương',
        shape_triangle: 'Tam giác',

        // Face Shape Descriptions
        desc_oval: 'Đường nét thon gọn như trái xoan',
        desc_round: 'Khuôn mặt tròn và mềm mại',
        desc_square: 'Hàm góc cạnh và mạnh mẽ',
        desc_long: 'Chiều dọc dài hơn chiều ngang',
        desc_heart: 'Trán rộng cằm nhọn',
        desc_diamond: 'Gò má cao cằm nhọn',
        desc_triangle: 'Hàm rộng hơn trán',

        // Wizard
        selectGender: 'Vui lòng chọn giới tính',
        uploadPhoto: 'Tải ảnh lên',
        or: 'hoặc',
        selfCheckBtn: 'Tự kiểm tra không cần ảnh',
        analyzing: 'AI đang phân tích...',
        selfCheckTitle: 'Khuôn mặt của bạn hình gì?',
        selfCheckDesc: 'Chọn hình dạng gần giống nhất.',
        styleCheck: 'Kiểm tra phong cách',
        myStyleCheck: 'Kiểm tra phong cách của tôi',
        uploadGuide: 'Vui lòng tải lên ảnh chính diện.',
        failAnalysis: 'Phân tích thất bại. Vui lòng kiểm tra ảnh.',
        aiAnalysisResult: 'Kết quả phân tích khuôn mặt AI',
        mainShape: 'Hình dạng chính',
        manualResult: 'Kết quả tự kiểm tra',
        selectedShape: 'Hình dạng đã chọn',
        resultDesc: '* Dựa trên kết quả phân tích và câu trả lời,',
        resultDescEnd: 'được đề xuất.',
        manualDesc: '* Kiểu tóc được đề xuất dựa trên lựa chọn của bạn.',
        simulateOnMyFace: 'Mô phỏng trên mặt tôi',
        requestTemplate: 'Mẫu yêu cầu salon',
        showDesigner: 'Vui lòng cho thợ làm tóc xem màn hình này.',
        maintenanceTip: 'Mẹo chăm sóc',
        otherRecs: 'Đề xuất khác',
    },
    th: {
        analysisResult: "ผลการวิเคราะห์",
        bestMatch: "เหมาะสมที่สุด",
        matchScore: "คะแนนความเข้ากัน",
        whyItFits: "ทำไมถึงเหมาะกับคุณ",
        aiGenerate: "ลองทรงผม AI",
        reset: "รีเซ็ต",
        download: "บันทึก",
        findSalon: "ค้นหาร้านทำผม",
        complementaryTips: "เคล็ดลับการจัดแต่งทรง",
        stylingDifficulty: "ความยากในการจัดทรง",
        subscribeTitle: "ปลดล็อกรายงานพรีเมียม",
        subscribeDesc: "ดูการวิเคราะห์ความสมมาตรของใบหน้าและสีส่วนบุคคลโดยละเอียด",
        subscribeBtn: "สมัครสมาชิก - 2,900 วอน/เดือน",
        // Logic / Tags
        'clean': 'สะอาด',
        'pro': 'มืออาชีพ',
        'short': 'ผมสั้น',
        'easy-care': 'ดูแลง่าย',
        'trendy': 'ทันสมัย',
        'manly': 'สมชายชาตรี',
        'soft': 'นุ่มนวล',
        'volume': 'มีวอลลุ่ม',
        'hip': 'ฮิป',
        'unique': 'ไม่เหมือนใคร',
        'classic': 'คลาสสิก',
        'feminine': 'ผู้หญิง',
        'chic': 'ชิค',
        'goddess': 'นางฟ้า',
        'cute': 'น่ารัก',
        'lovely': 'น่าเลิฟ',
        'elegant': 'สง่างาม',
        'mature': 'เป็นผู้ใหญ่',
        'pure': 'บริสุทธิ์',
        'boyish': 'บอยๆ',
        'styling': 'จัดทรง',
        'natural': 'ธรรมชาติ',
        'young': 'ดูเด็ก',
        'sharp': 'คมเข้ม',
        'medium-care': 'ดูแลปานกลาง',
        'high-care': 'ดูแลยาก',
        'flat': 'เรียบ',
        'retro': 'เรโทร',
        'daily': 'ประจำวัน',
        'long': 'ผมยาว',
        'medium': 'ผมประบ่า',
        // Reasons
        'reason_face_good': 'ช่วยแก้ไขรูปหน้าได้ดีเยี่ยม',
        'reason_face_bad': 'อาจเน้นจุดด้อยของรูปหน้า',
        'reason_texture_good': 'เหมาะกับสภาพเส้นผมปัจจุบัน',
        'reason_texture_bad': 'อาจไม่เหมาะกับสภาพเส้นผม',
        'reason_vibe_good': 'ตรงกับลุคที่ต้องการ',
        'reason_maintenance_bad': 'ต้องดูแลรักษาบ้าง',
        'reason_length_cut': 'ทรงผมสั้นที่คุณต้องการ',
        'reason_length_grow': 'ทรงผมยาวที่คุณต้องการ',
        'reason_length_keep': 'รักษาความยาวปัจจุบัน',

        // Landing Page
        landingTitle1: 'ค้นหา',
        landingTitle2: 'ทรงผมที่ใช่',
        landingSubtitle: 'AI วิเคราะห์รูปหน้าและสภาพเส้นผม\nเพื่อค้นหาทรงผมที่เหมาะกับคุณที่สุด',
        startAnalysis: 'เริ่มวิเคราะห์ฟรี',
        dataPrivacy: '*รูปภาพจะถูกประมวลผลในเครื่องและจะไม่ถูกบันทึกบนเซิร์ฟเวอร์',
        featureFace: 'วิเคราะห์ใบหน้า',
        featureStyle: 'แนะนำทรงผม',
        featureReport: 'รายงานแบบกำหนดเอง',
        male: 'ชาย',
        female: 'หญิง',
        shape_oval: 'หน้ารูปไข่',
        shape_round: 'หน้ากลม',
        shape_square: 'หน้าเหลี่ยม',
        shape_long: 'หน้ายาว',
        shape_heart: 'หน้ารูปหัวใจ',
        shape_diamond: 'หน้าเพชร',
        shape_triangle: 'หน้าสามเหลี่ยม',

        // Face Shape Descriptions
        desc_oval: 'รูปหน้าเรียวสวยเหมือนไข่',
        desc_round: 'หน้ากลมและดูนุ่มนวล',
        desc_square: 'กรามชัดและดูแข็งแรง',
        desc_long: 'ความยาวหน้ามากกว่าความกว้าง',
        desc_heart: 'หน้าผากกว้าง คางแหลม',
        desc_diamond: 'โหนกแก้มชัด คางแหลม',
        desc_triangle: 'กรามกว้างกว่าหน้าผาก',

        // Wizard
        selectGender: 'กรุณาเลือกเพศ',
        uploadPhoto: 'อัปโหลดรูปภาพ',
        or: 'หรือ',
        selfCheckBtn: 'ตรวจสอบด้วยตัวเอง (ไม่ใช้รูป)',
        analyzing: 'AI กำลังวิเคราะห์...',
        selfCheckTitle: 'รูปหน้าของคุณเป็นแบบไหน?',
        selfCheckDesc: 'เลือกรูปแบบที่ใกล้เคียงที่สุด',
        styleCheck: 'ตรวจสอบสไตล์',
        myStyleCheck: 'ตรวจสอบสไตล์ของฉัน',
        uploadGuide: 'กรุณาอัปโหลดรูปหน้าตรง',
        failAnalysis: 'การวิเคราะห์ใบหน้าล้มเหลว กรุณาตรวจสอบรูปภาพ',
        aiAnalysisResult: 'ผลการวิเคราะห์รูปหน้า AI',
        mainShape: 'รูปหน้าหลัก',
        manualResult: 'ผลการตรวจสอบด้วยตัวเอง',
        selectedShape: 'รูปหน้าที่เลือก',
        resultDesc: '* จากผลการวิเคราะห์และคำตอบของคุณ',
        resultDescEnd: 'แนะนำทรงนี้',
        manualDesc: '* ทรงผมที่แนะนำตามสิ่งที่คุณเลือก',
        simulateOnMyFace: 'จำลองบนใบหน้าของฉัน',
        requestTemplate: 'เทมเพลตคำขอร้านทำผม',
        showDesigner: 'กรุณาแสดงหน้าจอนี้ให้ช่างทำผมดู',
        maintenanceTip: 'เคล็ดลับการดูแล',
        otherRecs: 'คำแนะนำอื่นๆ',
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('ko'); // Default to Korean as requested

    const t = (key: string) => {
        // @ts-ignore
        const entry = translations[language];
        // Fallback to English if key missing in current lang
        // @ts-ignore
        return entry?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
