'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ko' | 'en' | 'ja' | 'zh' | 'vn' | 'th';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: Language; label: string; flag: string; }[] = [
    { code: 'ko', label: '한국어', flag: '🇰🇷' },
    { code: 'en', label: 'English', flag: '🇺🇸' },
    { code: 'ja', label: '日本語', flag: '🇯🇵' },
    { code: 'zh', label: '中文', flag: '🇨🇳' },
    { code: 'vn', label: 'Tiếng Việt', flag: '🇻🇳' },
    { code: 'th', label: 'ไทย', flag: '🇹🇭' },
];

export const translations = {
    en: {
        analysisResult: "Analysis Result",
        bestMatch: "BEST MATCH",
        matchScore: "Match Score",
        whyItFits: "Why it fits you",
        aiGenerate: "AI Generate",
        reset: "Reset",
        download: "Download",
        findSalon: "Find Salon",
        complementaryTips: "Complementary Tips",
        stylingDifficulty: "Styling Difficulty",
        subscribeTitle: "Unlock Premium Report",
        subscribeDesc: "Get detailed face symmetry & personal color analysis.",
        subscribeBtn: "Subscribe - $2.99/mo",
        // Logic / Tags
        'clean': 'Clean',
        'pro': 'Professional',
        'short': 'Short',
        'easy-care': 'Easy Care',
        'trendy': 'Trendy',
        'manly': 'Masculine',
        'soft': 'Soft',
        'volume': 'Volume',
        'hip': 'Hip',
        'unique': 'Unique',
        'classic': 'Classic',
        'feminine': 'Feminine',
        'chic': 'Chic',
        'goddess': 'Goddess',
        'cute': 'Cute',
        'lovely': 'Lovely',
        'elegant': 'Elegant',
        'mature': 'Mature',
        'pure': 'Pure',
        'boyish': 'Boyish',
        'styling': 'Styling',
        'natural': 'Natural',
        'young': 'Young',
        'sharp': 'Sharp',
        'medium-care': 'Medium Care',
        'high-care': 'High Care',
        'flat': 'Flat',
        'retro': 'Retro',
        'daily': 'Daily',
        'long': 'Long',
        'medium': 'Medium',
        // Reasons
        'reason_face_good': 'Great for your face shape',
        'reason_face_bad': 'May highlight face shape concerns',
        'reason_texture_good': 'Matches your hair texture',
        'reason_texture_bad': 'Texture mismatch',
        'reason_vibe_good': 'Matches desired vibe',
        'reason_maintenance_bad': 'High maintenance',
        'reason_length_cut': 'Good short option',
        'reason_length_grow': 'Good long option',
        'reason_length_keep': 'Maintains current length',

        // Result Card UI
        goodFor: 'Good For',
        avoidIf: 'Avoid If',
        saveCard: 'Save Card',
        share: 'Share',
        retry: 'Retry',
        hairFitTypeIndicator: 'HairFit Type Indicator',
        hairFitConsulting: 'HairFit AI Consulting',

        // Landing Page
        landingTitle1: 'Find Your',
        landingTitle2: 'Perfect Fit',
        landingSubtitle: 'AI analyzes your face shape and hair texture\nto find the perfect hairstyle for you.',
        startAnalysis: 'Start Free Analysis',
        dataPrivacy: '*Photos are processed locally and never saved on server.',
        featureFace: 'Face Analysis',
        featureStyle: 'Style Recs',
        featureReport: 'Custom Report',

        // Wizard
        selectGender: 'Select Gender',
        uploadPhoto: 'Upload Photo',
        or: 'or',
        selfCheckBtn: 'Self Check without Photo',
        analyzing: 'AI Analyzing...',
        selfCheckTitle: 'What is your face shape?',
        selfCheckDesc: 'Choose the shape that fits you best.',
        styleCheck: 'Style Check',
        myStyleCheck: 'My Style Check',
        uploadGuide: 'Please upload a front-facing photo.',
        failAnalysis: 'Analysis failed. Please check the photo.',
        aiAnalysisResult: 'AI Face Analysis Result',
        mainShape: 'Main Shape',
        manualResult: 'Self Check Result',
        selectedShape: 'Selected Shape',
        resultDesc: '* Based on the analysis and your answers, we recommend',
        resultDescEnd: '.',
        manualDesc: '* Recommended style based on your selection.',
        simulateOnMyFace: 'Simulate on my face',
        requestTemplate: 'Salon Request Template',
        showDesigner: 'Show this screen to your designer.',
        // Result Card UI
        detailedReport: 'Detailed Analysis Report',
        expertComment: 'Expert Comment',
        stylingTip: 'Styling Guide',
        maintenanceTip: 'Maintenance Tip',

        termsOfService: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',

        // Content
        howItWorksTitle: 'How It Works',
        howItWorksDesc: 'Simple 3-step process',
        step1Title: 'Upload Photo',
        step1Desc: 'Take a selfie or upload a photo. Images are processed locally and never saved.',
        step2Title: 'AI Analysis',
        step2Desc: 'Precise analysis of 21 face landmarks to identify your exact face shape.',
        step3Title: 'Get Recommendations',
        step3Desc: 'We recommend the perfect hairstyle based on your face shape, texture, and vibe.',
        whyHairFitTitle: 'Why HairFit?',
        seoText1: 'Finding the perfect hairstyle is hard. Have you ever been disappointed after bringing a celebrity photo to the salon? HairFit uses advanced AI to analyze objective data (face ratios, jaw angles) to find styles that maximize your charm.',
        seoText2: 'Check with HairFit before visiting the salon. Your best partner for a fail-proof makeover. Start now for free.',
        latestArticles: 'Latest Articles',
        faqTitle: 'FAQ',
        faq1Q: 'Is it really free?',
        faq1A: 'Yes, basic analysis and recommendations are 100% free.',
        faq2Q: 'Is my photo safe?',
        faq2A: 'Absolutely. All processing happens on your device. Photos are never uploaded to our servers.',
        faq3Q: 'Can I use it without a photo?',
        faq3A: 'Yes, try the "Self Check" mode to answer questions and get recommendations manually.',
        faq4Q: 'Does it work for both men and women?',
        faq4A: 'Yes, we have specialized databases for both genders to provide optimized recommendations for everyone.',

        // Survey (Male)
        sm_q1_title: 'How much forehead exposure?',
        sm_q1_opt_none: 'Cover Full',
        sm_q1_opt_none_desc: 'Shy about forehead',
        sm_q1_opt_little: 'Slightly Open',
        sm_q1_opt_little_desc: 'Not too open, not too closed',
        sm_q1_opt_full: 'Full Open',
        sm_q1_opt_full_desc: 'Confident with forehead',

        sm_q2_title: 'What vibe do you prefer?',
        sm_q2_opt_standard: 'Neat & Standard',
        sm_q2_opt_standard_desc: 'Standard handsome look',
        sm_q2_opt_character: 'Hip & Unique',
        sm_q2_opt_character_desc: 'Distinct self-style',
        sm_q2_opt_natural: 'Natural',
        sm_q2_opt_natural_desc: 'Effortless look',

        sm_q3_title: 'Styling time in morning?',
        sm_q3_opt_none: '3 Mins',
        sm_q3_opt_none_desc: 'Just shake and go',
        sm_q3_opt_basic: 'Blow Dry',
        sm_q3_opt_basic_desc: 'Can shape with dryer',
        sm_q3_opt_hard: 'Full Styling',
        sm_q3_opt_hard_desc: 'Wax/Spray is fine',

        // Survey (Female)
        sf_q1_title: 'Current (or desired) Length?',
        sf_q1_opt_short: 'Short/Bob',
        sf_q1_opt_short_desc: 'Fresh neck line',
        sf_q1_opt_medium: 'Medium',
        sf_q1_opt_medium_desc: 'Shoulder length',
        sf_q1_opt_long: 'Long',
        sf_q1_opt_long_desc: 'Below chest',

        sf_q2_title: 'Desired Vibe?',
        sf_q2_opt_lovely: 'Lovely/Cute',
        sf_q2_opt_lovely_desc: 'Adorable image',
        sf_q2_opt_chic: 'Chic/Hip',
        sf_q2_opt_chic_desc: 'Urban & Stylish',
        sf_q2_opt_innocent: 'Innocent/Natural',
        sf_q2_opt_innocent_desc: 'Clean & Soft',

        sf_q3_title: 'Styling Preference',
        sf_q3_opt_easy: 'Easy Dry',
        sf_q3_opt_easy_desc: 'Hate styling, comfort first',
        sf_q3_opt_hard: 'Iron/Dryer',
        sf_q3_opt_hard_desc: 'Beauty over comfort',
    },
    ko: {
        analysisResult: "분석 결과",
        bestMatch: "최고의 추천",
        matchScore: "일치도",
        whyItFits: "추천 이유",
        aiGenerate: "AI 가상 착용",
        reset: "초기화",
        download: "저장",
        findSalon: "미용실 찾기",
        complementaryTips: "스타일링 꿀팁",
        stylingDifficulty: "손질 난이도",
        subscribeTitle: "프리미엄 리포트 잠금 해제",
        subscribeDesc: "얼굴 비대칭 및 퍼스널 컬러 상세 분석을 확인하세요.",
        subscribeBtn: "구독하기 - 월 2,900원",

        // Result Card UI
        detailedReport: '상세 분석 리포트',
        expertComment: '전문가 분석 코멘트',
        stylingTip: '스타일링 가이드',
        maintenanceTip: '관리 및 유지 팁',

        // Logic / Tags
        'clean': '깔끔한',
        'pro': '전문적인',

        // Survey (Male - KO)
        sm_q1_title: 'Q1. 원하는 이마 노출 정도는?',
        sm_q1_opt_none: '완전 덮기',
        sm_q1_opt_none_desc: '이마 보이는 건 부끄러워요',
        sm_q1_opt_little: '살짝만 보이기',
        sm_q1_opt_little_desc: '답답한 건 싫지만 다 까긴 부담',
        sm_q1_opt_full: '시원하게 까기',
        sm_q1_opt_full_desc: '이마 미남, 자신감 뿜뿜',

        sm_q2_title: 'Q2. 평소 추구하는 분위기는?',
        sm_q2_opt_standard: '깔끔/단정',
        sm_q2_opt_standard_desc: '호불호 없는 훈남 스타일',
        sm_q2_opt_character: '힙함/개성',
        sm_q2_opt_character_desc: '나만의 색깔이 뚜렷했으면',
        sm_q2_opt_natural: '자연스러움',
        sm_q2_opt_natural_desc: '꾸민 듯 안 꾸민 듯 편안함',

        sm_q3_title: 'Q3. 아침에 머리 손질, 얼마나 가능?',
        sm_q3_opt_none: '3분 컷',
        sm_q3_opt_none_desc: '그냥 털고 나가고 싶어요',
        sm_q3_opt_basic: '드라이 정도는',
        sm_q3_opt_basic_desc: '말릴 때 모양 잡을 수 있어요',
        sm_q3_opt_hard: '각 잡고 꾸밈',
        sm_q3_opt_hard_desc: '왁스/스프레이 사용 가능!',

        // Survey (Female - KO)
        sf_q1_title: 'Q1. 현재(또는 원하는) 기장은?',
        sf_q1_opt_short: '숏/단발',
        sf_q1_opt_short_desc: '목선이 드러나는 산뜻한 기장',
        sf_q1_opt_medium: '중단발 (거지존)',
        sf_q1_opt_medium_desc: '어깨에 닿는 애매한 기장',
        sf_q1_opt_long: '장발',
        sf_q1_opt_long_desc: '가슴 아래로 내려오는 긴 머리',

        sf_q2_title: 'Q2. 원하는 분위기는?',
        sf_q2_opt_lovely: '러블리/큐티',
        sf_q2_opt_lovely_desc: '사랑스럽고 귀여운 느낌',
        sf_q2_opt_chic: '시크/힙',
        sf_q2_opt_chic_desc: '도시적이고 세련된 느낌',
        sf_q2_opt_innocent: '청순/자연스러움',
        sf_q2_opt_innocent_desc: '깨끗하고 부드러운 이미지',

        sf_q3_title: 'Q3. 손질 선호도',
        sf_q3_opt_easy: '털어 말리기만',
        sf_q3_opt_easy_desc: '손질 귀찮아요, 편한 게 최고',
        sf_q3_opt_hard: '고데기/드라기 가능',
        sf_q3_opt_hard_desc: '예뻐질 수 있다면 감수함!',
        'short': '짧은 기장',
        'easy-care': '손질 쉬움',
        'trendy': '트렌디',
        'manly': '남성적인',
        'soft': '의 부드러운',
        'volume': '볼륨감',
        'hip': '힙한',
        'unique': '유니크',
        'classic': '클래식',
        'feminine': '여성스러운',
        'chic': '시크한',
        'goddess': '여신머리',
        'cute': '귀여운',
        'lovely': '사랑스러운',
        'elegant': '우아한',
        'mature': '성숙한',
        'pure': '청순한',
        'boyish': '보이시',
        'styling': '스타일링',
        'natural': '자연스러운',
        'young': '어려보이는',
        'sharp': '날렵한',
        'medium-care': '손질 보통',
        'high-care': '손질 어려움',
        'flat': '플랫한',
        'retro': '레트로',
        'daily': '데일리',
        'long': '긴 기장',
        'medium': '중단발',
        // Reasons
        'reason_face_good': '얼굴형 보완에 탁월해요',
        'reason_face_bad': '얼굴형 단점이 부각될 수 있어요',
        'reason_texture_good': '현재 모발과 찰떡이에요',
        'reason_texture_bad': '모발 성질과 안 맞을 수 있어요',
        'reason_vibe_good': '원하는 분위기에 딱 맞아요',
        'reason_maintenance_bad': '손질이 조금 필요해요',
        'reason_length_cut': '원하시는 짧은 스타일이에요',
        'reason_length_grow': '원하시는 긴 스타일이에요',
        'reason_length_keep': '현재 기장을 유지해요',

        // Result Card UI
        goodFor: '추천 대상',
        avoidIf: '비추천 대상',
        saveCard: '카드 저장하기',
        share: '공유하기',
        retry: '다시 하기',
        hairFitTypeIndicator: 'HairFit Type Indicator',
        hairFitConsulting: 'HairFit AI Consulting',

        // Landing Page
        landingTitle1: '나만의',
        landingTitle2: '인생 머리 찾기',
        landingSubtitle: 'AI가 얼굴형, 두상, 모질을 분석하여\n당신에게 가장 잘 어울리는 인생 머리를 찾아드려요.',
        startAnalysis: '무료로 분석 시작하기',
        dataPrivacy: '*사진은 서버에 저장되지 않고 100% 안전하게 처리됩니다.',
        featureFace: '얼굴형 분석',
        featureStyle: '스타일 추천',
        featureReport: '맞춤 리포트',

        // Data Values
        male: '남성',
        female: '여성',
        shape_oval: '계란형',
        shape_round: '둥근형',
        shape_square: '각형',
        shape_long: '긴 얼굴형',
        shape_heart: '하트형',
        shape_diamond: '다이아몬드형',
        shape_triangle: '삼각형',

        // Wizard
        selectGender: '성별을 선택해주세요',
        uploadPhoto: '사진 업로드',
        or: '또는',
        selfCheckBtn: '사진 없이 자가진단하기',
        analyzing: 'AI 분석중...',
        selfCheckTitle: '본인의 얼굴형은?',
        selfCheckDesc: '가장 가깝다고 생각되는 형태를 골라주세요.',
        styleCheck: '스타일 체크',
        myStyleCheck: 'My 스타일 체크',
        uploadGuide: '정면 사진을 올려주세요.',
        failAnalysis: '얼굴 분석 실패. 사진을 확인해주세요.',
        aiAnalysisResult: 'AI 얼굴형 분석 결과',
        mainShape: 'Main Shape',
        manualResult: '자가진단 결과',
        selectedShape: '선택한 얼굴형',
        resultDesc: '* 위 분석 결과와 서베이 답변을 종합하여',
        resultDescEnd: '을(를) 추천했습니다.',
        manualDesc: '* 사용자가 선택한 얼굴형과 답변을 기반으로 추천된 스타일입니다.',
        simulateOnMyFace: '내 얼굴에 합성해보기',
        requestTemplate: '미용실 요청 템플릿',
        showDesigner: '디자이너에게 이 화면을 보여주세요.',
        maintenanceTip: 'Maintenance Tip',
        otherRecs: '다른 추천 스타일',

        // Face Shape Descriptions
        desc_oval: '계란처럼 갸름한 라인',
        desc_round: '둥글고 부드러운 인상',
        desc_square: '턱선이 각지고 강인함',
        desc_long: '가로보다 세로가 김',
        desc_heart: '이마가 넓고 턱이 뾰족',
        desc_diamond: '광대가 있고 턱이 뾰족',
        desc_triangle: '이마보다 턱이 넓음',
        termsOfService: '이용약관',
        privacyPolicy: '개인정보처리방침',

        // Content (SEO & FAQ)
        howItWorksTitle: '어떻게 작동하나요?',
        howItWorksDesc: '3단계로 완료되는 간단한 프로세스',
        step1Title: '사진 촬영/업로드',
        step1Desc: '정면 사진을 업로드하거나 간편하게 촬영하세요. 사진은 서버에 저장되지 않습니다.',
        step2Title: 'AI 얼굴형 분석',
        step2Desc: '21개의 얼굴 랜드마크를 정밀 분석하여 계란형, 둥근형, 각진형 등 정확한 얼굴형을 진단합니다.',
        step3Title: '인생 헤어 추천',
        step3Desc: '얼굴형과 모질, 그리고 선호하는 분위기를 종합하여 가장 잘 어울리는 헤어스타일을 제안합니다.',
        whyHairFitTitle: '왜 HairFit 인가요?',
        seoText1: '자신에게 어울리는 헤어스타일을 찾기란 쉽지 않습니다. 연예인 사진을 들고 미용실에 갔다가 실망한 적이 있으신가요? 헤어핏(HairFit)은 최신 AI 기술을 활용해 객관적인 데이터(얼굴 비율, 턱선 각도, 이마 넓이)를 기반으로 당신의 매력을 극대화할 수 있는 스타일을 찾아드립니다.',
        seoText2: '미용실에 가기 전, HairFit으로 미리 확인해 보세요. 실패 없는 스타일 변신을 위한 최고의 파트너가 되어드립니다. 지금 바로 무료로 시작해보세요.',
        latestArticles: '최신 블로그',
        faqTitle: '자주 묻는 질문 (FAQ)',
        faq1Q: '정말 무료인가요?',
        faq1A: '네, 기본적인 얼굴 분석과 스타일 추천 기능은 100% 무료로 제공됩니다. 일부 프리미엄 심층 분석(비대칭 분석 등)만 유료입니다.',
        faq2Q: '사진이 유출되지는 않나요?',
        faq2A: '걱정하지 마세요. HairFit은 모든 분석을 사용자의 기기(브라우저) 내에서 수행합니다. 사진은 서버로 전송되거나 저장되지 않습니다.',
        faq3Q: '사진을 업로드하지 않고도 이용할 수 있나요?',
        faq3A: '네, [사진 없이 자가진단하기] 기능을 통해 몇 가지 질문에 답하는 것만으로도 추천을 받을 수 있습니다.',
        faq4Q: '남성/여성 모두 가능한가요?',
        faq4A: '네, 성별에 따라 특화된 데이터베이스를 보유하고 있어 남녀 모두에게 최적화된 스타일을 추천해 드립니다.',
    },
    ja: {
        analysisResult: "分析結果",
        bestMatch: "ベストマッチ",
        matchScore: "マッチ度",
        whyItFits: "おすすめの理由",
        aiGenerate: "AI仮想試着",
        reset: "リセット",
        download: "保存",
        findSalon: "美容室を探す",
        complementaryTips: "スタイリングのヒント",
        stylingDifficulty: "スタイリング難易度",
        subscribeTitle: "プレミアムレポートを解除",
        subscribeDesc: "顔の非対称性とパーソナルカラーの詳細分析を確認しましょう。",
        subscribeBtn: "購読する - 月額 2,900ウォン",
        // Logic / Tags
        'clean': '清潔感',
        'pro': 'プロフェッショナル',
        'short': 'ショート',
        'easy-care': '手入れ簡単',
        'trendy': 'トレンディ',
        'manly': '男性的',
        'soft': '柔らかい',
        'volume': 'ボリューム',
        'hip': 'ヒップ',
        'unique': 'ユニーク',
        'classic': 'クラシック',
        'feminine': 'フェミニン',
        'chic': 'シック',
        'goddess': '女神ヘア',
        'cute': 'キュート',
        'lovely': 'ラブリー',
        'elegant': 'エレガント',
        'mature': '大人っぽい',
        'pure': '清楚',
        'boyish': 'ボーイッシュ',
        'styling': 'スタイリング',
        'natural': 'ナチュラル',
        'young': '若々しい',
        'sharp': 'シャープ',
        'medium-care': '手入れ普通',
        'high-care': '手入れ難しい',
        'flat': 'フラット',
        'retro': 'レトロ',
        'daily': 'デイリー',
        'long': 'ロング',
        'medium': 'ミディアム',
        // Reasons
        'reason_face_good': '顔型をきれいに見せます',
        'reason_face_bad': '顔型の短所が目立つ可能性があります',
        'reason_texture_good': '現在の髪質にぴったりです',
        'reason_texture_bad': '髪質に合わない可能性があります',
        'reason_vibe_good': '希望の雰囲気に合っています',
        'reason_maintenance_bad': '少し手入れが必要です',
        'reason_length_cut': '希望のショートスタイルです',
        'reason_length_grow': '希望のロングスタイルです',
        'reason_length_keep': '現在の長さを維持します',

        // Landing Page
        landingTitle1: '自分だけの',
        landingTitle2: '人生ヘア探し',
        landingSubtitle: 'AIが顔型、頭の形、髪質を分析して\nあなたにぴったりの人生ヘアを見つけます。',
        startAnalysis: '無料分析を始める',
        dataPrivacy: '*写真はサーバーに保存されず、安全に処理されます。',
        featureFace: '顔型分析',
        featureStyle: 'スタイル推奨',
        featureReport: 'カスタムレポート',
        male: '男性',
        female: '女性',
        shape_oval: '卵型',
        shape_round: '丸顔',
        shape_square: 'ベース型',
        shape_long: '面長',
        shape_heart: '逆三角形',
        shape_diamond: 'ひし形',
        shape_triangle: '三角形',

        // Wizard
        selectGender: '性別を選択してください',
        uploadPhoto: '写真をアップロード',
        or: 'または',
        selfCheckBtn: '写真なしで自己診断する',
        analyzing: 'AI分析中...',
        selfCheckTitle: 'あなたの顔型は？',
        selfCheckDesc: '最も近いと思う形を選んでください。',
        styleCheck: 'スタイルチェック',
        myStyleCheck: 'マイスタイルチェック',
        uploadGuide: '正面の写真をアップロードしてください。',
        failAnalysis: '顔分析失敗。写真を確認してください。',
        aiAnalysisResult: 'AI顔型分析結果',
        mainShape: 'メイン顔型',
        manualResult: '自己診断結果',
        selectedShape: '選択した顔型',
        resultDesc: '* 上記の分析結果とアンケート回答を総合して、',
        resultDescEnd: 'を推奨しました。',
        manualDesc: '* ユーザーが選択した顔型と回答に基づいて推奨されたスタイルです。',
        simulateOnMyFace: '自分の顔でシミュレーション',
        requestTemplate: '美容室リクエストテンプレート',
        showDesigner: '美容師にこの画面を見せてください。',
        maintenanceTip: '管理のヒント',
        otherRecs: '他のおすすめスタイル',
        // Face Shape Descriptions
        desc_oval: '卵のようにすっきりとしたライン',
        desc_round: '丸くて柔らかい印象',
        desc_square: '顎のラインが角ばっていて強い',
        desc_long: '横より縦が長い',
        desc_heart: '額が広く顎が尖っている',
        desc_diamond: '頬骨が出ていて顎が尖っている',
        desc_triangle: '額より顎が広い',
        termsOfService: '利用規約',
        privacyPolicy: 'プライバシーポリシー',

        // Survey (Male - JA)
        sm_q1_title: 'おでこはどれくらい出しますか？',
        sm_q1_opt_none: '完全に隠す',
        sm_q1_opt_none_desc: 'おでこは見せたくない',
        sm_q1_opt_little: '少し見せる（シースルー）',
        sm_q1_opt_little_desc: '全部隠すのは重いけど、全開は負担',
        sm_q1_opt_full: '全開（アップバング）',
        sm_q1_opt_full_desc: 'おでこを出して自信満々',

        sm_q2_title: 'どのような雰囲気が好きですか？',
        sm_q2_opt_standard: '清潔感・定番',
        sm_q2_opt_standard_desc: '誰からも好かれるスタイル',
        sm_q2_opt_character: '個性的・ヒップ',
        sm_q2_opt_character_desc: '自分だけのスタイル',
        sm_q2_opt_natural: 'ナチュラル',
        sm_q2_opt_natural_desc: '頑張りすぎない自然さ',

        sm_q3_title: '朝のスタイリング時間は？',
        sm_q3_opt_none: '3分以内',
        sm_q3_opt_none_desc: '乾かして終わり！',
        sm_q3_opt_basic: 'ドライヤーで整える',
        sm_q3_opt_basic_desc: '乾かす時に形を作る程度',
        sm_q3_opt_hard: 'しっかりセット',
        sm_q3_opt_hard_desc: 'ワックスやスプレーもOK',

        // Survey (Female - JA)
        sf_q1_title: '現在（または希望）の長さは？',
        sf_q1_opt_short: 'ショート/ボブ',
        sf_q1_opt_short_desc: '首元すっきり',
        sf_q1_opt_medium: 'ミディアム',
        sf_q1_opt_medium_desc: '肩につく長さ',
        sf_q1_opt_long: 'ロング',
        sf_q1_opt_long_desc: '胸より下',

        sf_q2_title: 'なりたい雰囲気は？',
        sf_q2_opt_lovely: 'ラブリー/キュート',
        sf_q2_opt_lovely_desc: '愛らしいイメージ',
        sf_q2_opt_chic: 'シック/クール',
        sf_q2_opt_chic_desc: '都会的で洗練された',
        sf_q2_opt_innocent: '清楚/ナチュラル',
        sf_q2_opt_innocent_desc: '清潔感と柔らかさ',

        sf_q3_title: 'スタイリングの好み',
        sf_q3_opt_easy: '乾かすだけ',
        sf_q3_opt_easy_desc: '楽なのが一番',
        sf_q3_opt_hard: 'アイロン/コテ使用',
        sf_q3_opt_hard_desc: '可愛くなるなら頑張れる',

        // Content
        howItWorksTitle: '使い方',
        howItWorksDesc: '3ステップで完了する簡単なプロセス',
        step1Title: '写真撮影/アップロード',
        step1Desc: '自撮りするか写真をアップロードしてください。写真はサーバーに保存されません。',
        step2Title: 'AI顔型分析',
        step2Desc: '21の顔ランドマークを精密分析し、正確な顔型を診断します。',
        step3Title: 'おすすめヘア',
        step3Desc: '顔型、髪質、好みの雰囲気を総合して、あなたにぴったりのスタイルを提案します。',
        whyHairFitTitle: 'なぜHairFitなのか？',
        seoText1: '自分に似合う髪型を見つけるのは難しいものです。芸能人の写真を持って美容室に行っても失敗したことはありませんか？HairFitは最新AI技術で客観的なデータ（顔の比率、顎の角度）に基づき、あなたの魅力を最大化するスタイルを見つけます。',
        seoText2: '美容室に行く前にHairFitで確認しましょう。失敗のないイメチェンのための最高のパートナーです。今すぐ無料でお試しください。',
        latestArticles: '最新記事',
        faqTitle: 'よくある質問 (FAQ)',
        faq1Q: '本当に無料ですか？',
        faq1A: 'はい、基本的な顔分析とスタイル提案は100%無料です。一部のプレミアム深層分析のみ有料です。',
        faq2Q: '写真は安全ですか？',
        faq2A: 'ご安心ください。HairFitはすべての分析をユーザーの端末内で行います。写真はサーバーに送信・保存されません。',
        faq3Q: '写真なしでも利用できますか？',
        faq3A: 'はい、「写真なしで自己診断」機能を使えば、いくつかの質問に答えるだけでおすすめを受け取れます。',
        faq4Q: '男性/女性どちらも可能ですか？',
        faq4A: 'はい、性別ごとに特化したデータベースを持っており、男女ともに最適化されたスタイルを提案します。',
    },
    zh: {
        analysisResult: "分析结果",
        bestMatch: "最佳推荐",
        matchScore: "匹配度",
        whyItFits: "推荐理由",
        aiGenerate: "AI虚拟试戴",
        reset: "重置",
        download: "保存",
        findSalon: "寻找理发店",
        complementaryTips: "造型小贴士",
        stylingDifficulty: "打理难度",
        subscribeTitle: "解锁高级报告",
        subscribeDesc: "查看面部不对称及个人色彩详细分析。",
        subscribeBtn: "订阅 - 2,900韩元/月",
        // Logic / Tags
        'clean': '干净',
        'pro': '专业',
        'short': '短发',
        'easy-care': '易打理',
        'trendy': '潮流',
        'manly': '男性化',
        'soft': '柔和',
        'volume': '蓬松',
        'hip': '嘻哈',
        'unique': '独特',
        'classic': '经典',
        'feminine': '女性化',
        'chic': '时尚',
        'goddess': '女神范',
        'cute': '可爱',
        'lovely': '甜美',
        'elegant': '优雅',
        'mature': '成熟',
        'pure': '清纯',
        'boyish': '少年感',
        'styling': '造型',
        'natural': '自然',
        'young': '减龄',
        'sharp': '利落',
        'medium-care': '打理普通',
        'high-care': '打理困难',
        'flat': '扁平',
        'retro': '复古',
        'daily': '日常',
        'long': '长发',
        'medium': '中长发',
        // Reasons
        'reason_face_good': '非常修饰脸型',
        'reason_face_bad': '可能会突出脸型缺点',
        'reason_texture_good': '非常适合当前发质',
        'reason_texture_bad': '可能不适合您的发质',
        'reason_vibe_good': '符合您想要的氛围',
        'reason_maintenance_bad': '需要一些打理',
        'reason_length_cut': '符合您想要的短发风格',
        'reason_length_grow': '符合您想要的长发风格',
        'reason_length_keep': '保持当前长度',

        // Landing Page
        landingTitle1: '寻找你的',
        landingTitle2: '人生发型',
        landingSubtitle: 'AI分析脸型、头型和发质\n为你找到最完美的人生发型。',
        startAnalysis: '开始免费分析',
        dataPrivacy: '*照片不会保存到服务器，100%安全处理。',
        featureFace: '脸型分析',
        featureStyle: '发型推荐',
        featureReport: '定制报告',
        male: '男性',
        female: '女性',
        shape_oval: '鹅蛋脸',
        shape_round: '圆脸',
        shape_square: '方脸',
        shape_long: '长脸',
        shape_heart: '心形脸',
        shape_diamond: '菱形脸',
        shape_triangle: '三角形脸',

        // Face Shape Descriptions
        desc_oval: '如鹅蛋般匀称的线条',
        desc_round: '圆润柔和的印象',
        desc_square: '下颌线条棱角分明',
        desc_long: '纵向比横向长',
        desc_heart: '额头宽下巴尖',
        desc_diamond: '颧骨突出下巴尖',
        desc_triangle: '下巴比额头宽',

        // Wizard
        selectGender: '请选择性别',
        uploadPhoto: '上传照片',
        or: '或',
        selfCheckBtn: '无照片自我诊断',
        analyzing: 'AI分析中...',
        selfCheckTitle: '你的脸型是？',
        selfCheckDesc: '请选择最接近的形状。',
        styleCheck: '风格检查',
        myStyleCheck: '我的风格检查',
        uploadGuide: '请上传正面照片。',
        failAnalysis: '脸部分析失败。请检查照片。',
        aiAnalysisResult: 'AI脸型分析结果',
        mainShape: '主要脸型',
        manualResult: '自我诊断结果',
        selectedShape: '选择的脸型',
        resultDesc: '* 综合以上分析结果和问卷回答，',
        resultDescEnd: '为您推荐。',
        manualDesc: '* 基于用户选择的脸型和回答推荐的风格。',
        simulateOnMyFace: '在我的脸上模拟',
        requestTemplate: '理发店请求模板',
        showDesigner: '请向发型师出示此屏幕。',
        maintenanceTip: '管理提示',
        otherRecs: '其他推荐风格',

        // Survey (Male - ZH)
        sm_q1_title: '您希望露出多少额头？',
        sm_q1_opt_none: '完全遮盖',
        sm_q1_opt_none_desc: '不想露额头',
        sm_q1_opt_little: '稍微露出',
        sm_q1_opt_little_desc: '不想太闷，也不想全露',
        sm_q1_opt_full: '完全露出',
        sm_q1_opt_full_desc: '对自己额头有自信',

        sm_q2_title: '您喜欢什么风格？',
        sm_q2_opt_standard: '干净/标准',
        sm_q2_opt_standard_desc: '人见人爱的帅哥风格',
        sm_q2_opt_character: '个性/潮流',
        sm_q2_opt_character_desc: '想要独特的风格',
        sm_q2_opt_natural: '自然',
        sm_q2_opt_natural_desc: '毫不费力的舒适感',

        sm_q3_title: '早上有多少时间打理头发？',
        sm_q3_opt_none: '3分钟搞定',
        sm_q3_opt_none_desc: '只想吹干就走',
        sm_q3_opt_basic: '简单吹整',
        sm_q3_opt_basic_desc: '吹干时抓一下型',
        sm_q3_opt_hard: '精心造型',
        sm_q3_opt_hard_desc: '发蜡/发胶都可以！',

        // Survey (Female - ZH)
        sf_q1_title: '当前（或想要）的长度？',
        sf_q1_opt_short: '短发/波波头',
        sf_q1_opt_short_desc: '清爽的颈部线条',
        sf_q1_opt_medium: '中长发',
        sf_q1_opt_medium_desc: '齐肩的长度',
        sf_q1_opt_long: '长发',
        sf_q1_opt_long_desc: '过胸的长发',

        sf_q2_title: '想要的氛围？',
        sf_q2_opt_lovely: '可爱/甜美',
        sf_q2_opt_lovely_desc: '惹人喜爱的形象',
        sf_q2_opt_chic: '干练/酷飒',
        sf_q2_opt_chic_desc: '都市时尚感',
        sf_q2_opt_innocent: '清纯/自然',
        sf_q2_opt_innocent_desc: '干净柔和的形象',

        sf_q3_title: '打理偏好',
        sf_q3_opt_easy: '吹干即可',
        sf_q3_opt_easy_desc: '讨厌麻烦，舒服第一',
        sf_q3_opt_hard: '卷发棒/吹风机',
        sf_q3_opt_hard_desc: '为了变美可以忍受！',

        // Content
        howItWorksTitle: '使用方法',
        howItWorksDesc: '简单三步即可完成',
        step1Title: '拍摄/上传照片',
        step1Desc: '请自拍或上传照片。照片不会保存到服务器。',
        step2Title: 'AI脸型分析',
        step2Desc: '包含21个面部关键点的精密分析，准确诊断您的脸型。',
        step3Title: '人生发型推荐',
        step3Desc: '综合脸型、发质和喜欢的氛围，为您推荐最适合的发型。',
        whyHairFitTitle: '为什么选择HairFit？',
        seoText1: '找到适合自己的发型并不容易。您是否曾带着明星照片去理发店却感到失望？HairFit利用最新AI技术，基于客观数据（面部比例、下颌角度）找到能最大化您魅力的发型。',
        seoText2: '去理发店前，先用HairFit确认一下。为您打造零失败的形象变身。立即免费开始。',
        faqTitle: '常见问题 (FAQ)',
        faq1Q: '真的免费吗？',
        faq1A: '是的，基本的面部分析和发型推荐功能100%免费。仅部分高级深度分析付费。',
        faq2Q: '照片安全吗？',
        faq2A: '请放心。HairFit的所有分析都在用户设备（浏览器）内进行。照片不会发送或保存到服务器。',
        faq3Q: '可以不用照片吗？',
        faq3A: '是的，通过[无照片自我诊断]功能，只需回答几个问题即可获得推荐。',
        faq4Q: '男女都可以使用吗？',
        faq4A: '是的，我们拥有针对性别的专门数据库，为男女用户提供优化的风格推荐。',
    },
    vn: {
        analysisResult: "Kết Quả Phân Tích",
        bestMatch: "Phù Hợp Nhất",
        matchScore: "Điểm Phù Hợp",
        whyItFits: "Lý Do Phù Hợp",
        aiGenerate: "Thử Tóc AI",
        reset: "Đặt Lại",
        download: "Lưu",
        findSalon: "Tìm Salon",
        complementaryTips: "Mẹo Tạo Kiểu",
        stylingDifficulty: "Độ Khó Tạo Kiểu",
        subscribeTitle: "Mở Khóa Báo Cáo VIP",
        subscribeDesc: "Xem phân tích chi tiết bất đối xứng và màu sắc cá nhân.",
        subscribeBtn: "Đăng Ký - 2,900 KRW/tháng",
        // Logic / Tags
        'clean': 'Gọn gàng',
        'pro': 'Chuyên nghiệp',
        'short': 'Tóc ngắn',
        'easy-care': 'Dễ chăm sóc',
        'trendy': 'Thời thượng',
        'manly': 'Nam tính',
        'soft': 'Mềm mại',
        'volume': 'Phồng',
        'hip': 'Hip',
        'unique': 'Độc đáo',
        'classic': 'Cổ điển',
        'feminine': 'Nữ tính',
        'chic': 'Sang trọng',
        'goddess': 'Nữ thần',
        'cute': 'Dễ thương',
        'lovely': 'Đáng yêu',
        'elegant': 'Thanh lịch',
        'mature': 'Trưởng thành',
        'pure': 'Trong sáng',
        'boyish': 'Nghịch ngợm',
        'styling': 'Tạo kiểu',
        'natural': 'Tự nhiên',
        'young': 'Trẻ trung',
        'sharp': 'Sắc sảo',
        'medium-care': 'Chăm sóc bình thường',
        'high-care': 'Khó chăm sóc',
        'flat': 'Phẳng',
        'retro': 'Cổ điển',
        'daily': 'Hàng ngày',
        'long': 'Tóc dài',
        'medium': 'Tóc lỡ',
        // Reasons
        'reason_face_good': 'Tuyệt vời cho khuôn mặt của bạn',
        'reason_face_bad': 'Có thể làm lộ khuyết điểm khuôn mặt',
        'reason_texture_good': 'Phù hợp với chất tóc hiện tại',
        'reason_texture_bad': 'Không phù hợp với chất tóc',
        'reason_vibe_good': 'Phù hợp với phong cách mong muốn',
        'reason_maintenance_bad': 'Cần chăm sóc kỹ',
        'reason_length_cut': 'Kiểu tóc ngắn bạn muốn',
        'reason_length_grow': 'Kiểu tóc dài bạn muốn',
        'reason_length_keep': 'Giữ nguyên độ dài hiện tại',

        // Landing Page
        landingTitle1: 'Tìm Kiếm',
        landingTitle2: 'Kiểu Tóc Hoàn Hảo',
        landingSubtitle: 'AI phân tích khuôn mặt và chất tóc\nđể tìm kiểu tóc phù hợp nhất cho bạn.',
        startAnalysis: 'Bắt Đầu Phân Tích Miễn Phí',
        dataPrivacy: '*Ảnh được xử lý cục bộ và không bao giờ lưu trên máy chủ.',
        featureFace: 'Phân Tích Mặt',
        featureStyle: 'Gợi Ý Kiểu',
        featureReport: 'Báo Cáo Riêng',
        male: 'Nam',
        female: 'Nữ',
        shape_oval: 'Trái xoan',
        shape_round: 'Tròn',
        shape_square: 'Vuông',
        shape_long: 'Dài',
        shape_heart: 'Trái tim',
        shape_diamond: 'Kim cương',
        shape_triangle: 'Tam giác',

        // Face Shape Descriptions
        desc_oval: 'Đường nét thon gọn như trái xoan',
        desc_round: 'Khuôn mặt tròn và mềm mại',
        desc_square: 'Hàm góc cạnh và mạnh mẽ',
        desc_long: 'Chiều dọc dài hơn chiều ngang',
        desc_heart: 'Trán rộng cằm nhọn',
        desc_diamond: 'Gò má cao cằm nhọn',
        desc_triangle: 'Hàm rộng hơn trán',

        // Wizard
        selectGender: 'Vui lòng chọn giới tính',
        uploadPhoto: 'Tải ảnh lên',
        or: 'hoặc',
        selfCheckBtn: 'Tự kiểm tra không cần ảnh',
        analyzing: 'AI đang phân tích...',
        selfCheckTitle: 'Khuôn mặt của bạn hình gì?',
        selfCheckDesc: 'Chọn hình dạng gần giống nhất.',
        styleCheck: 'Kiểm tra phong cách',
        myStyleCheck: 'Kiểm tra phong cách của tôi',
        uploadGuide: 'Vui lòng tải lên ảnh chính diện.',
        failAnalysis: 'Phân tích thất bại. Vui lòng kiểm tra ảnh.',
        aiAnalysisResult: 'Kết quả phân tích khuôn mặt AI',
        mainShape: 'Hình dạng chính',
        manualResult: 'Kết quả tự kiểm tra',
        selectedShape: 'Hình dạng đã chọn',
        resultDesc: '* Dựa trên kết quả phân tích và câu trả lời,',
        resultDescEnd: 'được đề xuất.',
        manualDesc: '* Kiểu tóc được đề xuất dựa trên lựa chọn của bạn.',
        simulateOnMyFace: 'Mô phỏng trên mặt tôi',
        requestTemplate: 'Mẫu yêu cầu salon',
        showDesigner: 'Vui lòng cho thợ làm tóc xem màn hình này.',
        maintenanceTip: 'Mẹo chăm sóc',
        otherRecs: 'Đề xuất khác',

        // Survey (Male - VN)
        sm_q1_title: 'Bạn muốn lộ trán bao nhiêu?',
        sm_q1_opt_none: 'Che kín',
        sm_q1_opt_none_desc: 'Ngại lộ trán',
        sm_q1_opt_little: 'Thấy một chút',
        sm_q1_opt_little_desc: 'Không quá kín, không quá hở',
        sm_q1_opt_full: 'Lộ hoàn toàn',
        sm_q1_opt_full_desc: 'Tự tin với vầng trán',

        sm_q2_title: 'Bạn thích phong cách nào?',
        sm_q2_opt_standard: 'Gọn gàng & Chuẩn mực',
        sm_q2_opt_standard_desc: 'Kiểu tóc đẹp trai tiêu chuẩn',
        sm_q2_opt_character: 'Cá tính & Độc đáo',
        sm_q2_opt_character_desc: 'Phong cách riêng biệt',
        sm_q2_opt_natural: 'Tự nhiên',
        sm_q2_opt_natural_desc: 'Đẹp không cần cố gắng',

        sm_q3_title: 'Thời gian tạo kiểu tóc buổi sáng?',
        sm_q3_opt_none: '3 phút',
        sm_q3_opt_none_desc: 'Chỉ cần vuốt và đi',
        sm_q3_opt_basic: 'Sấy nhẹ',
        sm_q3_opt_basic_desc: 'Có thể tạo kiểu bằng máy sấy',
        sm_q3_opt_hard: 'Tạo kiểu kỹ',
        sm_q3_opt_hard_desc: 'Sáp/Gôm không thành vấn đề',

        // Survey (Female - VN)
        sf_q1_title: 'Độ dài hiện tại (hoặc mong muốn)?',
        sf_q1_opt_short: 'Ngắn/Bob',
        sf_q1_opt_short_desc: 'Lộ đường cổ trẻ trung',
        sf_q1_opt_medium: 'Vừa (Ngang vai)',
        sf_q1_opt_medium_desc: 'Độ dài chạm vai',
        sf_q1_opt_long: 'Dài',
        sf_q1_opt_long_desc: 'Dài qua ngực',

        sf_q2_title: 'Phong cách mong muốn?',
        sf_q2_opt_lovely: 'Đáng yêu/Dễ thương',
        sf_q2_opt_lovely_desc: 'Hình ảnh ngọt ngào',
        sf_q2_opt_chic: 'Sành điệu/Cá tính',
        sf_q2_opt_chic_desc: 'Thành thị & Thời trang',
        sf_q2_opt_innocent: 'Ngây thơ/Tự nhiên',
        sf_q2_opt_innocent_desc: 'Sạch sẽ & Nhẹ nhàng',

        sf_q3_title: 'Sở thích tạo kiểu',
        sf_q3_opt_easy: 'Sấy khô đơn giản',
        sf_q3_opt_easy_desc: 'Ghét cầu kỳ, thoải mái là nhất',
        sf_q3_opt_hard: 'Máy uốn/Máy sấy',
        sf_q3_opt_hard_desc: 'Đẹp là được!',

        // Content
        howItWorksTitle: 'Cách hoạt động',
        howItWorksDesc: 'Quy trình đơn giản 3 bước',
        step1Title: 'Chụp/Tải ảnh lên',
        step1Desc: 'Chụp selfie hoặc tải ảnh lên. Ảnh không được lưu trên máy chủ.',
        step2Title: 'Phân tích khuôn mặt AI',
        step2Desc: 'Phân tích chính xác 21 điểm mốc trên khuôn mặt để chẩn đoán chính xác hình dạng khuôn mặt của bạn.',
        step3Title: 'Đề xuất kiểu tóc',
        step3Desc: 'Đề xuất kiểu tóc phù hợp nhất dựa trên hình dạng khuôn mặt, chất tóc và phong cách ưa thích.',
        whyHairFitTitle: 'Tại sao là HairFit?',
        seoText1: 'Tìm kiếm kiểu tóc phù hợp không phải là điều dễ dàng. Bạn đã bao giờ thất vọng khi mang ảnh người nổi tiếng đến tiệm làm tóc chưa? HairFit sử dụng công nghệ AI tiên tiến để phân tích dữ liệu khách quan (tỷ lệ khuôn mặt, góc hàm) để tìm ra phong cách tối đa hóa sức hấp dẫn của bạn.',
        seoText2: 'Kiểm tra với HairFit trước khi đến tiệm làm tóc. Đối tác tốt nhất cho sự thay đổi phong cách không thất bại. Bắt đầu miễn phí ngay.',
        faqTitle: 'Câu hỏi thường gặp (FAQ)',
        faq1Q: 'Nó có thực sự miễn phí không?',
        faq1A: 'Vâng, phân tích khuôn mặt cơ bản và đề xuất phong cách là miễn phí 100%. Chỉ một số phân tích chuyên sâu cao cấp là trả phí.',
        faq2Q: 'Ảnh của tôi có an toàn không?',
        faq2A: 'Đừng lo lắng. HairFit thực hiện tất cả các phân tích trên thiết bị của bạn. Ảnh không được gửi hoặc lưu vào máy chủ.',
        faq3Q: 'Tôi có thể sử dụng mà không cần ảnh không?',
        faq3A: 'Vâng, hãy thử chế độ "Tự kiểm tra" để trả lời các câu hỏi và nhận đề xuất thủ công.',
        faq4Q: 'Cả nam và nữ đều dùng được chứ?',
        faq4A: 'Vâng, chúng tôi có cơ sở dữ liệu chuyên biệt cho cả hai giới để cung cấp các đề xuất tối ưu cho mọi người.',
    },
    th: {
        analysisResult: "ผลการวิเคราะห์",
        bestMatch: "เหมาะสมที่สุด",
        matchScore: "คะแนนความเข้ากัน",
        whyItFits: "ทำไมถึงเหมาะกับคุณ",
        aiGenerate: "ลองทรงผม AI",
        reset: "รีเซ็ต",
        download: "บันทึก",
        findSalon: "ค้นหาร้านทำผม",
        complementaryTips: "เคล็ดลับการจัดแต่งทรง",
        stylingDifficulty: "ความยากในการจัดทรง",
        subscribeTitle: "ปลดล็อกรายงานพรีเมียม",
        subscribeDesc: "ดูการวิเคราะห์ความสมมาตรของใบหน้าและสีส่วนบุคคลโดยละเอียด",
        subscribeBtn: "สมัครสมาชิก - 2,900 วอน/เดือน",
        // Logic / Tags
        'clean': 'สะอาด',
        'pro': 'มืออาชีพ',
        'short': 'ผมสั้น',
        'easy-care': 'ดูแลง่าย',
        'trendy': 'ทันสมัย',
        'manly': 'สมชายชาตรี',
        'soft': 'นุ่มนวล',
        'volume': 'มีวอลลุ่ม',
        'hip': 'ฮิป',
        'unique': 'ไม่เหมือนใคร',
        'classic': 'คลาสสิก',
        'feminine': 'ผู้หญิง',
        'chic': 'ชิค',
        'goddess': 'นางฟ้า',
        'cute': 'น่ารัก',
        'lovely': 'น่าเลิฟ',
        'elegant': 'สง่างาม',
        'mature': 'เป็นผู้ใหญ่',
        'pure': 'บริสุทธิ์',
        'boyish': 'บอยๆ',
        'styling': 'จัดทรง',
        'natural': 'ธรรมชาติ',
        'young': 'ดูเด็ก',
        'sharp': 'คมเข้ม',
        'medium-care': 'ดูแลปานกลาง',
        'high-care': 'ดูแลยาก',
        'flat': 'เรียบ',
        'retro': 'เรโทร',
        'daily': 'ประจำวัน',
        'long': 'ผมยาว',
        'medium': 'ผมประบ่า',
        // Reasons
        'reason_face_good': 'ช่วยแก้ไขรูปหน้าได้ดีเยี่ยม',
        'reason_face_bad': 'อาจเน้นจุดด้อยของรูปหน้า',
        'reason_texture_good': 'เหมาะกับสภาพเส้นผมปัจจุบัน',
        'reason_texture_bad': 'อาจไม่เหมาะกับสภาพเส้นผม',
        'reason_vibe_good': 'ตรงกับลุคที่ต้องการ',
        'reason_maintenance_bad': 'ต้องดูแลรักษาบ้าง',
        'reason_length_cut': 'ทรงผมสั้นที่คุณต้องการ',
        'reason_length_grow': 'ทรงผมยาวที่คุณต้องการ',
        'reason_length_keep': 'รักษาความยาวปัจจุบัน',

        // Landing Page
        landingTitle1: 'ค้นหา',
        landingTitle2: 'ทรงผมที่ใช่',
        landingSubtitle: 'AI วิเคราะห์รูปหน้าและสภาพเส้นผม\nเพื่อค้นหาทรงผมที่เหมาะกับคุณที่สุด',
        startAnalysis: 'เริ่มวิเคราะห์ฟรี',
        dataPrivacy: '*รูปภาพจะถูกประมวลผลในเครื่องและจะไม่ถูกบันทึกบนเซิร์ฟเวอร์',
        featureFace: 'วิเคราะห์ใบหน้า',
        featureStyle: 'แนะนำทรงผม',
        featureReport: 'รายงานแบบกำหนดเอง',
        male: 'ชาย',
        female: 'หญิง',
        shape_oval: 'หน้ารูปไข่',
        shape_round: 'หน้ากลม',
        shape_square: 'หน้าเหลี่ยม',
        shape_long: 'หน้ายาว',
        shape_heart: 'หน้ารูปหัวใจ',
        shape_diamond: 'หน้าเพชร',
        shape_triangle: 'หน้าสามเหลี่ยม',

        // Face Shape Descriptions
        desc_oval: 'รูปหน้าเรียวสวยเหมือนไข่',
        desc_round: 'หน้ากลมและดูนุ่มนวล',
        desc_square: 'กรามชัดและดูแข็งแรง',
        desc_long: 'ความยาวหน้ามากกว่าความกว้าง',
        desc_heart: 'หน้าผากกว้าง คางแหลม',
        desc_diamond: 'โหนกแก้มชัด คางแหลม',
        desc_triangle: 'กรามกว้างกว่าหน้าผาก',

        // Wizard
        selectGender: 'กรุณาเลือกเพศ',
        uploadPhoto: 'อัปโหลดรูปภาพ',
        or: 'หรือ',
        selfCheckBtn: 'ตรวจสอบด้วยตัวเอง (ไม่ใช้รูป)',
        analyzing: 'AI กำลังวิเคราะห์...',
        selfCheckTitle: 'รูปหน้าของคุณเป็นแบบไหน?',
        selfCheckDesc: 'เลือกรูปแบบที่ใกล้เคียงที่สุด',
        styleCheck: 'ตรวจสอบสไตล์',
        myStyleCheck: 'ตรวจสอบสไตล์ของฉัน',
        uploadGuide: 'กรุณาอัปโหลดรูปหน้าตรง',
        failAnalysis: 'การวิเคราะห์ใบหน้าล้มเหลว กรุณาตรวจสอบรูปภาพ',
        aiAnalysisResult: 'ผลการวิเคราะห์รูปหน้า AI',
        mainShape: 'รูปหน้าหลัก',
        manualResult: 'ผลการตรวจสอบด้วยตัวเอง',
        selectedShape: 'รูปหน้าที่เลือก',
        resultDesc: '* จากผลการวิเคราะห์และคำตอบของคุณ',
        resultDescEnd: 'แนะนำทรงนี้',
        manualDesc: '* ทรงผมที่แนะนำตามสิ่งที่คุณเลือก',
        simulateOnMyFace: 'จำลองบนใบหน้าของฉัน',
        requestTemplate: 'เทมเพลตคำขอร้านทำผม',
        showDesigner: 'กรุณาแสดงหน้าจอนี้ให้ช่างทำผมดู',
        maintenanceTip: 'เคล็ดลับการดูแล',
        otherRecs: 'คำแนะนำอื่นๆ',

        // Survey (Male - TH)
        sm_q1_title: 'คุณต้องการเปิดหน้าผากมากแค่ไหน?',
        sm_q1_opt_none: 'ปิดหมด',
        sm_q1_opt_none_desc: 'เขินที่จะเปิดหน้าผาก',
        sm_q1_opt_little: 'เปิดนิดหน่อย',
        sm_q1_opt_little_desc: 'ไม่ปิดทึบ แต่ก็ไม่เปิดหมด',
        sm_q1_opt_full: 'เปิดหมด',
        sm_q1_opt_full_desc: 'มั่นใจในหน้าผาก',

        sm_q2_title: 'คุณชอบสไตล์แบบไหน?',
        sm_q2_opt_standard: 'เรียบร้อย & มาตรฐาน',
        sm_q2_opt_standard_desc: 'ลุคหล่อมาตรฐาน',
        sm_q2_opt_character: 'ฮิป & มีเอกลักษณ์',
        sm_q2_opt_character_desc: 'สไตล์ชัดเจนในแบบตัวเอง',
        sm_q2_opt_natural: 'ธรรมชาติ',
        sm_q2_opt_natural_desc: 'ดูดีแบบไม่ต้องพยายาม',

        sm_q3_title: 'เวลาเซ็ตผมตอนเช้า?',
        sm_q3_opt_none: '3 นาทีจบ',
        sm_q3_opt_none_desc: 'แค่เป่าแล้วไปได้เลย',
        sm_q3_opt_basic: 'ไดร์จัดทรง',
        sm_q3_opt_basic_desc: 'จัดทรงด้วยไดร์ได้',
        sm_q3_opt_hard: 'เซ็ตเต็มที่',
        sm_q3_opt_hard_desc: 'แว็กซ์/สเปรย์ จัดมาเลย',

        // Survey (Female - TH)
        sf_q1_title: 'ความยาวปัจจุบัน (หรือที่ต้องการ)?',
        sf_q1_opt_short: 'สั้น/บ๊อบ',
        sf_q1_opt_short_desc: 'โชว์ต้นคอสดใส',
        sf_q1_opt_medium: 'ประบ่า',
        sf_q1_opt_medium_desc: 'ความยาวระดูไหล่',
        sf_q1_opt_long: 'ยาว',
        sf_q1_opt_long_desc: 'ยาวเลยหน้าอก',

        sf_q2_title: 'สไตล์ที่ต้องการ?',
        sf_q2_opt_lovely: 'น่ารัก/คิวท์',
        sf_q2_opt_lovely_desc: 'ลุคน่าทะนุถนอม',
        sf_q2_opt_chic: 'ชิค/เก๋',
        sf_q2_opt_chic_desc: 'ทันสมัย & ดูดี',
        sf_q2_opt_innocent: 'ใสซื่อ/ธรรมชาติ',
        sf_q2_opt_innocent_desc: 'สะอาด & นุ่มนวล',

        sf_q3_title: 'ความชอบในการเซ็ตผม',
        sf_q3_opt_easy: 'เป่าแห้งง่ายๆ',
        sf_q3_opt_easy_desc: 'ไม่ชอบเซ็ต ขอสบายไว้ก่อน',
        sf_q3_opt_hard: 'ใช้แกนร้อน/ไดร์',
        sf_q3_opt_hard_desc: 'เพื่อความสวย ยอมทน!',

        // Content
        howItWorksTitle: 'วิธีการใช้งาน',
        howItWorksDesc: 'ขั้นตอนง่ายๆ 3 ขั้นตอน',
        step1Title: 'ถ่าย/อัปโหลดรูป',
        step1Desc: 'ถ่ายเซลฟี่หรืออัปโหลดรูปภาพ รูปภาพจะไม่ถูกบันทึกบนเซิร์ฟเวอร์',
        step2Title: 'วิเคราะห์ใบหน้า AI',
        step2Desc: 'วิเคราะห์จุดบนใบหน้า 21 จุดอย่างละเอียดเพื่อวินิจฉัยรูปหน้าของคุณอย่างแม่นยำ',
        step3Title: 'แนะนำทรงผม',
        step3Desc: 'แนะนำทรงผมที่เหมาะสมที่สุดโดยพิจารณาจากรูปหน้า สภาพเส้นผม และสไตล์ที่คุณชอบ',
        whyHairFitTitle: 'ทำไมต้อง HairFit?',
        seoText1: 'การหาทรงผมที่เหมาะกับตัวเองไม่ใช่เรื่องง่าย เคยไหมที่เอารูปดาราไปให้ช่างดูแล้วต้องผิดหวัง? HairFit ใช้เทคโนโลยี AI ล่าสุดเพื่อวิเคราะห์ข้อมูลเชิงวัตถุวิสัย (สัดส่วนใบหน้า มุมกราม) เพื่อค้นหาสไตล์ที่ดึงเสน่ห์ของคุณออกมาได้มากที่สุด',
        seoText2: 'เช็คกับ HairFit ก่อนไปร้านทำผม เพื่อนคู่ใจที่ดีที่สุดสำหรับการเปลี่ยนลุคที่ไม่มีคำว่าพลาด เริ่มต้นใช้งานฟรีได้เลย',
        faqTitle: 'คำถามที่พบบ่อย (FAQ)',
        faq1Q: 'ฟรีจริงหรือ?',
        faq1A: 'ใช่ การวิเคราะห์ใบหน้าพื้นฐานและการแนะนำสไตล์นั้นฟรี 100% มีเพียงการวิเคราะห์เชิงลึกระดับพรีเมียมเท่านั้นที่มีค่าใช้จ่าย',
        faq2Q: 'รูปถ่ายปลอดภัยหรือไม่?',
        faq2A: 'ไม่ต้องกังวล HairFit ประมวลผลการวิเคราะห์ทั้งหมดบนอุปกรณ์ของคุณ รูปภาพจะไม่ถูกส่งหรือบันทึกไปยังเซิร์ฟเวอร์',
        faq3Q: 'ใช้งานโดยไม่มีรูปถ่ายได้ไหม?',
        faq3A: 'ได้ ลองใช้โหมด "ตรวจสอบด้วยตัวเอง" เพื่อตอบคำถามและรับคำแนะนำ',
        faq4Q: 'ใช้ได้ทั้งชายและหญิงไหม?',
        faq4A: 'ใช่ เรามีฐานข้อมูลเฉพาะสำหรับทั้งสองเพศเพื่อแนะนำสไตล์ที่เหมาะสมที่สุดสำหรับทุกคน',
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('ko'); // Default to Korean as requested

    const t = (key: string) => {
        // @ts-ignore
        const entry = translations[language];
        // Fallback to English if key missing in current lang
        // @ts-ignore
        return entry?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
